/*
OKX v5 API

OpenAPI specification for Okx exchange - Rest API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rest

import (
	"encoding/json"
)

// checks if the CreateAccountPositionMarginBalanceV5RespDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAccountPositionMarginBalanceV5RespDataInner{}

// CreateAccountPositionMarginBalanceV5RespDataInner struct for CreateAccountPositionMarginBalanceV5RespDataInner
type CreateAccountPositionMarginBalanceV5RespDataInner struct {
	// Amount to be increase or decrease
	Amt *string `json:"amt,omitempty"`
	// Currency
	Ccy *string `json:"ccy,omitempty"`
	// Instrument ID
	InstId *string `json:"instId,omitempty"`
	// Real leverage after the margin adjustment
	Leverage *string `json:"leverage,omitempty"`
	// Position side, `long`  `short`
	PosSide *string `json:"posSide,omitempty"`
	// `add`: add margin  `reduce`: reduce margin
	Type *string `json:"type,omitempty"`
}

// NewCreateAccountPositionMarginBalanceV5RespDataInner instantiates a new CreateAccountPositionMarginBalanceV5RespDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAccountPositionMarginBalanceV5RespDataInner() *CreateAccountPositionMarginBalanceV5RespDataInner {
	this := CreateAccountPositionMarginBalanceV5RespDataInner{}
	var amt string = ""
	this.Amt = &amt
	var ccy string = ""
	this.Ccy = &ccy
	var instId string = ""
	this.InstId = &instId
	var leverage string = ""
	this.Leverage = &leverage
	var posSide string = ""
	this.PosSide = &posSide
	var type_ string = ""
	this.Type = &type_
	return &this
}

// NewCreateAccountPositionMarginBalanceV5RespDataInnerWithDefaults instantiates a new CreateAccountPositionMarginBalanceV5RespDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAccountPositionMarginBalanceV5RespDataInnerWithDefaults() *CreateAccountPositionMarginBalanceV5RespDataInner {
	this := CreateAccountPositionMarginBalanceV5RespDataInner{}
	var amt string = ""
	this.Amt = &amt
	var ccy string = ""
	this.Ccy = &ccy
	var instId string = ""
	this.InstId = &instId
	var leverage string = ""
	this.Leverage = &leverage
	var posSide string = ""
	this.PosSide = &posSide
	var type_ string = ""
	this.Type = &type_
	return &this
}

// GetAmt returns the Amt field value if set, zero value otherwise.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) GetAmt() string {
	if o == nil || IsNil(o.Amt) {
		var ret string
		return ret
	}
	return *o.Amt
}

// GetAmtOk returns a tuple with the Amt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) GetAmtOk() (*string, bool) {
	if o == nil || IsNil(o.Amt) {
		return nil, false
	}
	return o.Amt, true
}

// HasAmt returns a boolean if a field has been set.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) HasAmt() bool {
	if o != nil && !IsNil(o.Amt) {
		return true
	}

	return false
}

// SetAmt gets a reference to the given string and assigns it to the Amt field.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) SetAmt(v string) {
	o.Amt = &v
}

// GetCcy returns the Ccy field value if set, zero value otherwise.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) GetCcy() string {
	if o == nil || IsNil(o.Ccy) {
		var ret string
		return ret
	}
	return *o.Ccy
}

// GetCcyOk returns a tuple with the Ccy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) GetCcyOk() (*string, bool) {
	if o == nil || IsNil(o.Ccy) {
		return nil, false
	}
	return o.Ccy, true
}

// HasCcy returns a boolean if a field has been set.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) HasCcy() bool {
	if o != nil && !IsNil(o.Ccy) {
		return true
	}

	return false
}

// SetCcy gets a reference to the given string and assigns it to the Ccy field.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) SetCcy(v string) {
	o.Ccy = &v
}

// GetInstId returns the InstId field value if set, zero value otherwise.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) GetInstId() string {
	if o == nil || IsNil(o.InstId) {
		var ret string
		return ret
	}
	return *o.InstId
}

// GetInstIdOk returns a tuple with the InstId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) GetInstIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstId) {
		return nil, false
	}
	return o.InstId, true
}

// HasInstId returns a boolean if a field has been set.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) HasInstId() bool {
	if o != nil && !IsNil(o.InstId) {
		return true
	}

	return false
}

// SetInstId gets a reference to the given string and assigns it to the InstId field.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) SetInstId(v string) {
	o.InstId = &v
}

// GetLeverage returns the Leverage field value if set, zero value otherwise.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) GetLeverage() string {
	if o == nil || IsNil(o.Leverage) {
		var ret string
		return ret
	}
	return *o.Leverage
}

// GetLeverageOk returns a tuple with the Leverage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) GetLeverageOk() (*string, bool) {
	if o == nil || IsNil(o.Leverage) {
		return nil, false
	}
	return o.Leverage, true
}

// HasLeverage returns a boolean if a field has been set.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) HasLeverage() bool {
	if o != nil && !IsNil(o.Leverage) {
		return true
	}

	return false
}

// SetLeverage gets a reference to the given string and assigns it to the Leverage field.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) SetLeverage(v string) {
	o.Leverage = &v
}

// GetPosSide returns the PosSide field value if set, zero value otherwise.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) GetPosSide() string {
	if o == nil || IsNil(o.PosSide) {
		var ret string
		return ret
	}
	return *o.PosSide
}

// GetPosSideOk returns a tuple with the PosSide field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) GetPosSideOk() (*string, bool) {
	if o == nil || IsNil(o.PosSide) {
		return nil, false
	}
	return o.PosSide, true
}

// HasPosSide returns a boolean if a field has been set.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) HasPosSide() bool {
	if o != nil && !IsNil(o.PosSide) {
		return true
	}

	return false
}

// SetPosSide gets a reference to the given string and assigns it to the PosSide field.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) SetPosSide(v string) {
	o.PosSide = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreateAccountPositionMarginBalanceV5RespDataInner) SetType(v string) {
	o.Type = &v
}

func (o CreateAccountPositionMarginBalanceV5RespDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAccountPositionMarginBalanceV5RespDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amt) {
		toSerialize["amt"] = o.Amt
	}
	if !IsNil(o.Ccy) {
		toSerialize["ccy"] = o.Ccy
	}
	if !IsNil(o.InstId) {
		toSerialize["instId"] = o.InstId
	}
	if !IsNil(o.Leverage) {
		toSerialize["leverage"] = o.Leverage
	}
	if !IsNil(o.PosSide) {
		toSerialize["posSide"] = o.PosSide
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableCreateAccountPositionMarginBalanceV5RespDataInner struct {
	value *CreateAccountPositionMarginBalanceV5RespDataInner
	isSet bool
}

func (v NullableCreateAccountPositionMarginBalanceV5RespDataInner) Get() *CreateAccountPositionMarginBalanceV5RespDataInner {
	return v.value
}

func (v *NullableCreateAccountPositionMarginBalanceV5RespDataInner) Set(val *CreateAccountPositionMarginBalanceV5RespDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAccountPositionMarginBalanceV5RespDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAccountPositionMarginBalanceV5RespDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAccountPositionMarginBalanceV5RespDataInner(val *CreateAccountPositionMarginBalanceV5RespDataInner) *NullableCreateAccountPositionMarginBalanceV5RespDataInner {
	return &NullableCreateAccountPositionMarginBalanceV5RespDataInner{value: val, isSet: true}
}

func (v NullableCreateAccountPositionMarginBalanceV5RespDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAccountPositionMarginBalanceV5RespDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


