/*
OKX v5 API

OpenAPI specification for Okx exchange - Rest API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rest

import (
	"encoding/json"
)

// checks if the CreateAccountPositionBuilderV5RespDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAccountPositionBuilderV5RespDataInner{}

// CreateAccountPositionBuilderV5RespDataInner struct for CreateAccountPositionBuilderV5RespDataInner
type CreateAccountPositionBuilderV5RespDataInner struct {
	// Leverage of the account
	AcctLever *string `json:"acctLever,omitempty"`
	// Asset info
	Assets []CreateAccountPositionBuilderV5RespDataInnerAssetsInner `json:"assets,omitempty"`
	// Borrow MMR (`USD`) for the account
	BorrowMmr *string `json:"borrowMmr,omitempty"`
	// Derivatives MMR (`USD`) for the account
	DerivMmr *string `json:"derivMmr,omitempty"`
	// Adjusted equity (`USD`) for the account
	Eq *string `json:"eq,omitempty"`
	// Cross margin ratio for the account
	MarginRatio *string `json:"marginRatio,omitempty"`
	// Position info  Only applicable to `Multi-currency margin`
	Positions []CreateAccountPositionBuilderV5RespDataInnerPositionsInner `json:"positions,omitempty"`
	// Risk unit info
	RiskUnitData []CreateAccountPositionBuilderV5RespDataInnerRiskUnitDataInner `json:"riskUnitData,omitempty"`
	// Total IMR (`USD`) for the account
	TotalImr *string `json:"totalImr,omitempty"`
	// Total MMR (`USD`) for the account
	TotalMmr *string `json:"totalMmr,omitempty"`
	// Update time for the account, Unix timestamp format in milliseconds, e.g. `1597026383085`
	Ts *string `json:"ts,omitempty"`
	// UPL for the account
	Upl *string `json:"upl,omitempty"`
}

// NewCreateAccountPositionBuilderV5RespDataInner instantiates a new CreateAccountPositionBuilderV5RespDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAccountPositionBuilderV5RespDataInner() *CreateAccountPositionBuilderV5RespDataInner {
	this := CreateAccountPositionBuilderV5RespDataInner{}
	var acctLever string = ""
	this.AcctLever = &acctLever
	var borrowMmr string = ""
	this.BorrowMmr = &borrowMmr
	var derivMmr string = ""
	this.DerivMmr = &derivMmr
	var eq string = ""
	this.Eq = &eq
	var marginRatio string = ""
	this.MarginRatio = &marginRatio
	var totalImr string = ""
	this.TotalImr = &totalImr
	var totalMmr string = ""
	this.TotalMmr = &totalMmr
	var ts string = ""
	this.Ts = &ts
	var upl string = ""
	this.Upl = &upl
	return &this
}

// NewCreateAccountPositionBuilderV5RespDataInnerWithDefaults instantiates a new CreateAccountPositionBuilderV5RespDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAccountPositionBuilderV5RespDataInnerWithDefaults() *CreateAccountPositionBuilderV5RespDataInner {
	this := CreateAccountPositionBuilderV5RespDataInner{}
	var acctLever string = ""
	this.AcctLever = &acctLever
	var borrowMmr string = ""
	this.BorrowMmr = &borrowMmr
	var derivMmr string = ""
	this.DerivMmr = &derivMmr
	var eq string = ""
	this.Eq = &eq
	var marginRatio string = ""
	this.MarginRatio = &marginRatio
	var totalImr string = ""
	this.TotalImr = &totalImr
	var totalMmr string = ""
	this.TotalMmr = &totalMmr
	var ts string = ""
	this.Ts = &ts
	var upl string = ""
	this.Upl = &upl
	return &this
}

// GetAcctLever returns the AcctLever field value if set, zero value otherwise.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetAcctLever() string {
	if o == nil || IsNil(o.AcctLever) {
		var ret string
		return ret
	}
	return *o.AcctLever
}

// GetAcctLeverOk returns a tuple with the AcctLever field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetAcctLeverOk() (*string, bool) {
	if o == nil || IsNil(o.AcctLever) {
		return nil, false
	}
	return o.AcctLever, true
}

// HasAcctLever returns a boolean if a field has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) HasAcctLever() bool {
	if o != nil && !IsNil(o.AcctLever) {
		return true
	}

	return false
}

// SetAcctLever gets a reference to the given string and assigns it to the AcctLever field.
func (o *CreateAccountPositionBuilderV5RespDataInner) SetAcctLever(v string) {
	o.AcctLever = &v
}

// GetAssets returns the Assets field value if set, zero value otherwise.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetAssets() []CreateAccountPositionBuilderV5RespDataInnerAssetsInner {
	if o == nil || IsNil(o.Assets) {
		var ret []CreateAccountPositionBuilderV5RespDataInnerAssetsInner
		return ret
	}
	return o.Assets
}

// GetAssetsOk returns a tuple with the Assets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetAssetsOk() ([]CreateAccountPositionBuilderV5RespDataInnerAssetsInner, bool) {
	if o == nil || IsNil(o.Assets) {
		return nil, false
	}
	return o.Assets, true
}

// HasAssets returns a boolean if a field has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) HasAssets() bool {
	if o != nil && !IsNil(o.Assets) {
		return true
	}

	return false
}

// SetAssets gets a reference to the given []CreateAccountPositionBuilderV5RespDataInnerAssetsInner and assigns it to the Assets field.
func (o *CreateAccountPositionBuilderV5RespDataInner) SetAssets(v []CreateAccountPositionBuilderV5RespDataInnerAssetsInner) {
	o.Assets = v
}

// GetBorrowMmr returns the BorrowMmr field value if set, zero value otherwise.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetBorrowMmr() string {
	if o == nil || IsNil(o.BorrowMmr) {
		var ret string
		return ret
	}
	return *o.BorrowMmr
}

// GetBorrowMmrOk returns a tuple with the BorrowMmr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetBorrowMmrOk() (*string, bool) {
	if o == nil || IsNil(o.BorrowMmr) {
		return nil, false
	}
	return o.BorrowMmr, true
}

// HasBorrowMmr returns a boolean if a field has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) HasBorrowMmr() bool {
	if o != nil && !IsNil(o.BorrowMmr) {
		return true
	}

	return false
}

// SetBorrowMmr gets a reference to the given string and assigns it to the BorrowMmr field.
func (o *CreateAccountPositionBuilderV5RespDataInner) SetBorrowMmr(v string) {
	o.BorrowMmr = &v
}

// GetDerivMmr returns the DerivMmr field value if set, zero value otherwise.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetDerivMmr() string {
	if o == nil || IsNil(o.DerivMmr) {
		var ret string
		return ret
	}
	return *o.DerivMmr
}

// GetDerivMmrOk returns a tuple with the DerivMmr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetDerivMmrOk() (*string, bool) {
	if o == nil || IsNil(o.DerivMmr) {
		return nil, false
	}
	return o.DerivMmr, true
}

// HasDerivMmr returns a boolean if a field has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) HasDerivMmr() bool {
	if o != nil && !IsNil(o.DerivMmr) {
		return true
	}

	return false
}

// SetDerivMmr gets a reference to the given string and assigns it to the DerivMmr field.
func (o *CreateAccountPositionBuilderV5RespDataInner) SetDerivMmr(v string) {
	o.DerivMmr = &v
}

// GetEq returns the Eq field value if set, zero value otherwise.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetEq() string {
	if o == nil || IsNil(o.Eq) {
		var ret string
		return ret
	}
	return *o.Eq
}

// GetEqOk returns a tuple with the Eq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetEqOk() (*string, bool) {
	if o == nil || IsNil(o.Eq) {
		return nil, false
	}
	return o.Eq, true
}

// HasEq returns a boolean if a field has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) HasEq() bool {
	if o != nil && !IsNil(o.Eq) {
		return true
	}

	return false
}

// SetEq gets a reference to the given string and assigns it to the Eq field.
func (o *CreateAccountPositionBuilderV5RespDataInner) SetEq(v string) {
	o.Eq = &v
}

// GetMarginRatio returns the MarginRatio field value if set, zero value otherwise.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetMarginRatio() string {
	if o == nil || IsNil(o.MarginRatio) {
		var ret string
		return ret
	}
	return *o.MarginRatio
}

// GetMarginRatioOk returns a tuple with the MarginRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetMarginRatioOk() (*string, bool) {
	if o == nil || IsNil(o.MarginRatio) {
		return nil, false
	}
	return o.MarginRatio, true
}

// HasMarginRatio returns a boolean if a field has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) HasMarginRatio() bool {
	if o != nil && !IsNil(o.MarginRatio) {
		return true
	}

	return false
}

// SetMarginRatio gets a reference to the given string and assigns it to the MarginRatio field.
func (o *CreateAccountPositionBuilderV5RespDataInner) SetMarginRatio(v string) {
	o.MarginRatio = &v
}

// GetPositions returns the Positions field value if set, zero value otherwise.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetPositions() []CreateAccountPositionBuilderV5RespDataInnerPositionsInner {
	if o == nil || IsNil(o.Positions) {
		var ret []CreateAccountPositionBuilderV5RespDataInnerPositionsInner
		return ret
	}
	return o.Positions
}

// GetPositionsOk returns a tuple with the Positions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetPositionsOk() ([]CreateAccountPositionBuilderV5RespDataInnerPositionsInner, bool) {
	if o == nil || IsNil(o.Positions) {
		return nil, false
	}
	return o.Positions, true
}

// HasPositions returns a boolean if a field has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) HasPositions() bool {
	if o != nil && !IsNil(o.Positions) {
		return true
	}

	return false
}

// SetPositions gets a reference to the given []CreateAccountPositionBuilderV5RespDataInnerPositionsInner and assigns it to the Positions field.
func (o *CreateAccountPositionBuilderV5RespDataInner) SetPositions(v []CreateAccountPositionBuilderV5RespDataInnerPositionsInner) {
	o.Positions = v
}

// GetRiskUnitData returns the RiskUnitData field value if set, zero value otherwise.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetRiskUnitData() []CreateAccountPositionBuilderV5RespDataInnerRiskUnitDataInner {
	if o == nil || IsNil(o.RiskUnitData) {
		var ret []CreateAccountPositionBuilderV5RespDataInnerRiskUnitDataInner
		return ret
	}
	return o.RiskUnitData
}

// GetRiskUnitDataOk returns a tuple with the RiskUnitData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetRiskUnitDataOk() ([]CreateAccountPositionBuilderV5RespDataInnerRiskUnitDataInner, bool) {
	if o == nil || IsNil(o.RiskUnitData) {
		return nil, false
	}
	return o.RiskUnitData, true
}

// HasRiskUnitData returns a boolean if a field has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) HasRiskUnitData() bool {
	if o != nil && !IsNil(o.RiskUnitData) {
		return true
	}

	return false
}

// SetRiskUnitData gets a reference to the given []CreateAccountPositionBuilderV5RespDataInnerRiskUnitDataInner and assigns it to the RiskUnitData field.
func (o *CreateAccountPositionBuilderV5RespDataInner) SetRiskUnitData(v []CreateAccountPositionBuilderV5RespDataInnerRiskUnitDataInner) {
	o.RiskUnitData = v
}

// GetTotalImr returns the TotalImr field value if set, zero value otherwise.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetTotalImr() string {
	if o == nil || IsNil(o.TotalImr) {
		var ret string
		return ret
	}
	return *o.TotalImr
}

// GetTotalImrOk returns a tuple with the TotalImr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetTotalImrOk() (*string, bool) {
	if o == nil || IsNil(o.TotalImr) {
		return nil, false
	}
	return o.TotalImr, true
}

// HasTotalImr returns a boolean if a field has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) HasTotalImr() bool {
	if o != nil && !IsNil(o.TotalImr) {
		return true
	}

	return false
}

// SetTotalImr gets a reference to the given string and assigns it to the TotalImr field.
func (o *CreateAccountPositionBuilderV5RespDataInner) SetTotalImr(v string) {
	o.TotalImr = &v
}

// GetTotalMmr returns the TotalMmr field value if set, zero value otherwise.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetTotalMmr() string {
	if o == nil || IsNil(o.TotalMmr) {
		var ret string
		return ret
	}
	return *o.TotalMmr
}

// GetTotalMmrOk returns a tuple with the TotalMmr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetTotalMmrOk() (*string, bool) {
	if o == nil || IsNil(o.TotalMmr) {
		return nil, false
	}
	return o.TotalMmr, true
}

// HasTotalMmr returns a boolean if a field has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) HasTotalMmr() bool {
	if o != nil && !IsNil(o.TotalMmr) {
		return true
	}

	return false
}

// SetTotalMmr gets a reference to the given string and assigns it to the TotalMmr field.
func (o *CreateAccountPositionBuilderV5RespDataInner) SetTotalMmr(v string) {
	o.TotalMmr = &v
}

// GetTs returns the Ts field value if set, zero value otherwise.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetTs() string {
	if o == nil || IsNil(o.Ts) {
		var ret string
		return ret
	}
	return *o.Ts
}

// GetTsOk returns a tuple with the Ts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetTsOk() (*string, bool) {
	if o == nil || IsNil(o.Ts) {
		return nil, false
	}
	return o.Ts, true
}

// HasTs returns a boolean if a field has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) HasTs() bool {
	if o != nil && !IsNil(o.Ts) {
		return true
	}

	return false
}

// SetTs gets a reference to the given string and assigns it to the Ts field.
func (o *CreateAccountPositionBuilderV5RespDataInner) SetTs(v string) {
	o.Ts = &v
}

// GetUpl returns the Upl field value if set, zero value otherwise.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetUpl() string {
	if o == nil || IsNil(o.Upl) {
		var ret string
		return ret
	}
	return *o.Upl
}

// GetUplOk returns a tuple with the Upl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) GetUplOk() (*string, bool) {
	if o == nil || IsNil(o.Upl) {
		return nil, false
	}
	return o.Upl, true
}

// HasUpl returns a boolean if a field has been set.
func (o *CreateAccountPositionBuilderV5RespDataInner) HasUpl() bool {
	if o != nil && !IsNil(o.Upl) {
		return true
	}

	return false
}

// SetUpl gets a reference to the given string and assigns it to the Upl field.
func (o *CreateAccountPositionBuilderV5RespDataInner) SetUpl(v string) {
	o.Upl = &v
}

func (o CreateAccountPositionBuilderV5RespDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAccountPositionBuilderV5RespDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AcctLever) {
		toSerialize["acctLever"] = o.AcctLever
	}
	if !IsNil(o.Assets) {
		toSerialize["assets"] = o.Assets
	}
	if !IsNil(o.BorrowMmr) {
		toSerialize["borrowMmr"] = o.BorrowMmr
	}
	if !IsNil(o.DerivMmr) {
		toSerialize["derivMmr"] = o.DerivMmr
	}
	if !IsNil(o.Eq) {
		toSerialize["eq"] = o.Eq
	}
	if !IsNil(o.MarginRatio) {
		toSerialize["marginRatio"] = o.MarginRatio
	}
	if !IsNil(o.Positions) {
		toSerialize["positions"] = o.Positions
	}
	if !IsNil(o.RiskUnitData) {
		toSerialize["riskUnitData"] = o.RiskUnitData
	}
	if !IsNil(o.TotalImr) {
		toSerialize["totalImr"] = o.TotalImr
	}
	if !IsNil(o.TotalMmr) {
		toSerialize["totalMmr"] = o.TotalMmr
	}
	if !IsNil(o.Ts) {
		toSerialize["ts"] = o.Ts
	}
	if !IsNil(o.Upl) {
		toSerialize["upl"] = o.Upl
	}
	return toSerialize, nil
}

type NullableCreateAccountPositionBuilderV5RespDataInner struct {
	value *CreateAccountPositionBuilderV5RespDataInner
	isSet bool
}

func (v NullableCreateAccountPositionBuilderV5RespDataInner) Get() *CreateAccountPositionBuilderV5RespDataInner {
	return v.value
}

func (v *NullableCreateAccountPositionBuilderV5RespDataInner) Set(val *CreateAccountPositionBuilderV5RespDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAccountPositionBuilderV5RespDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAccountPositionBuilderV5RespDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAccountPositionBuilderV5RespDataInner(val *CreateAccountPositionBuilderV5RespDataInner) *NullableCreateAccountPositionBuilderV5RespDataInner {
	return &NullableCreateAccountPositionBuilderV5RespDataInner{value: val, isSet: true}
}

func (v NullableCreateAccountPositionBuilderV5RespDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAccountPositionBuilderV5RespDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


