/*
Okx Rest API

OpenAPI specification for Okx cryptocurrency exchange - Rest API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rest

import (
	"encoding/json"
)

// checks if the GetSprdSpreadsV5RespDataLegsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSprdSpreadsV5RespDataLegsInner{}

// GetSprdSpreadsV5RespDataLegsInner struct for GetSprdSpreadsV5RespDataLegsInner
type GetSprdSpreadsV5RespDataLegsInner struct {
	// Instrument ID, e.g. BTC-USD-SWAP
	InstId *string `json:"instId,omitempty"`
	// The direction of the leg of the spread. Valid Values include `buy` and `sell`.
	Side *string `json:"side,omitempty"`
}

// NewGetSprdSpreadsV5RespDataLegsInner instantiates a new GetSprdSpreadsV5RespDataLegsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSprdSpreadsV5RespDataLegsInner() *GetSprdSpreadsV5RespDataLegsInner {
	this := GetSprdSpreadsV5RespDataLegsInner{}
	var instId string = ""
	this.InstId = &instId
	var side string = ""
	this.Side = &side
	return &this
}

// NewGetSprdSpreadsV5RespDataLegsInnerWithDefaults instantiates a new GetSprdSpreadsV5RespDataLegsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSprdSpreadsV5RespDataLegsInnerWithDefaults() *GetSprdSpreadsV5RespDataLegsInner {
	this := GetSprdSpreadsV5RespDataLegsInner{}
	var instId string = ""
	this.InstId = &instId
	var side string = ""
	this.Side = &side
	return &this
}

// GetInstId returns the InstId field value if set, zero value otherwise.
func (o *GetSprdSpreadsV5RespDataLegsInner) GetInstId() string {
	if o == nil || IsNil(o.InstId) {
		var ret string
		return ret
	}
	return *o.InstId
}

// GetInstIdOk returns a tuple with the InstId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSprdSpreadsV5RespDataLegsInner) GetInstIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstId) {
		return nil, false
	}
	return o.InstId, true
}

// HasInstId returns a boolean if a field has been set.
func (o *GetSprdSpreadsV5RespDataLegsInner) HasInstId() bool {
	if o != nil && !IsNil(o.InstId) {
		return true
	}

	return false
}

// SetInstId gets a reference to the given string and assigns it to the InstId field.
func (o *GetSprdSpreadsV5RespDataLegsInner) SetInstId(v string) {
	o.InstId = &v
}

// GetSide returns the Side field value if set, zero value otherwise.
func (o *GetSprdSpreadsV5RespDataLegsInner) GetSide() string {
	if o == nil || IsNil(o.Side) {
		var ret string
		return ret
	}
	return *o.Side
}

// GetSideOk returns a tuple with the Side field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSprdSpreadsV5RespDataLegsInner) GetSideOk() (*string, bool) {
	if o == nil || IsNil(o.Side) {
		return nil, false
	}
	return o.Side, true
}

// HasSide returns a boolean if a field has been set.
func (o *GetSprdSpreadsV5RespDataLegsInner) HasSide() bool {
	if o != nil && !IsNil(o.Side) {
		return true
	}

	return false
}

// SetSide gets a reference to the given string and assigns it to the Side field.
func (o *GetSprdSpreadsV5RespDataLegsInner) SetSide(v string) {
	o.Side = &v
}

func (o GetSprdSpreadsV5RespDataLegsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSprdSpreadsV5RespDataLegsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InstId) {
		toSerialize["instId"] = o.InstId
	}
	if !IsNil(o.Side) {
		toSerialize["side"] = o.Side
	}
	return toSerialize, nil
}

type NullableGetSprdSpreadsV5RespDataLegsInner struct {
	value *GetSprdSpreadsV5RespDataLegsInner
	isSet bool
}

func (v NullableGetSprdSpreadsV5RespDataLegsInner) Get() *GetSprdSpreadsV5RespDataLegsInner {
	return v.value
}

func (v *NullableGetSprdSpreadsV5RespDataLegsInner) Set(val *GetSprdSpreadsV5RespDataLegsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSprdSpreadsV5RespDataLegsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSprdSpreadsV5RespDataLegsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSprdSpreadsV5RespDataLegsInner(val *GetSprdSpreadsV5RespDataLegsInner) *NullableGetSprdSpreadsV5RespDataLegsInner {
	return &NullableGetSprdSpreadsV5RespDataLegsInner{value: val, isSet: true}
}

func (v NullableGetSprdSpreadsV5RespDataLegsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSprdSpreadsV5RespDataLegsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


