/*
Okx Rest API

OpenAPI specification for Okx cryptocurrency exchange - Rest API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rest

import (
	"encoding/json"
)

// checks if the CreateTradeBatchOrdersV5RespDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTradeBatchOrdersV5RespDataInner{}

// CreateTradeBatchOrdersV5RespDataInner struct for CreateTradeBatchOrdersV5RespDataInner
type CreateTradeBatchOrdersV5RespDataInner struct {
	// Client Order ID as assigned by the client
	ClOrdId *string `json:"clOrdId,omitempty"`
	// Order ID
	OrdId *string `json:"ordId,omitempty"`
	// The code of the event execution result, `0` means success.
	SCode *string `json:"sCode,omitempty"`
	// Rejection or success message of event execution.
	SMsg *string `json:"sMsg,omitempty"`
	// Order tag
	Tag *string `json:"tag,omitempty"`
	// Timestamp when the order request processing is finished by our system, Unix timestamp format in milliseconds, e.g. `1597026383085`
	Ts *string `json:"ts,omitempty"`
}

// NewCreateTradeBatchOrdersV5RespDataInner instantiates a new CreateTradeBatchOrdersV5RespDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTradeBatchOrdersV5RespDataInner() *CreateTradeBatchOrdersV5RespDataInner {
	this := CreateTradeBatchOrdersV5RespDataInner{}
	var clOrdId string = ""
	this.ClOrdId = &clOrdId
	var ordId string = ""
	this.OrdId = &ordId
	var sCode string = ""
	this.SCode = &sCode
	var sMsg string = ""
	this.SMsg = &sMsg
	var tag string = ""
	this.Tag = &tag
	var ts string = ""
	this.Ts = &ts
	return &this
}

// NewCreateTradeBatchOrdersV5RespDataInnerWithDefaults instantiates a new CreateTradeBatchOrdersV5RespDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTradeBatchOrdersV5RespDataInnerWithDefaults() *CreateTradeBatchOrdersV5RespDataInner {
	this := CreateTradeBatchOrdersV5RespDataInner{}
	var clOrdId string = ""
	this.ClOrdId = &clOrdId
	var ordId string = ""
	this.OrdId = &ordId
	var sCode string = ""
	this.SCode = &sCode
	var sMsg string = ""
	this.SMsg = &sMsg
	var tag string = ""
	this.Tag = &tag
	var ts string = ""
	this.Ts = &ts
	return &this
}

// GetClOrdId returns the ClOrdId field value if set, zero value otherwise.
func (o *CreateTradeBatchOrdersV5RespDataInner) GetClOrdId() string {
	if o == nil || IsNil(o.ClOrdId) {
		var ret string
		return ret
	}
	return *o.ClOrdId
}

// GetClOrdIdOk returns a tuple with the ClOrdId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTradeBatchOrdersV5RespDataInner) GetClOrdIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClOrdId) {
		return nil, false
	}
	return o.ClOrdId, true
}

// HasClOrdId returns a boolean if a field has been set.
func (o *CreateTradeBatchOrdersV5RespDataInner) HasClOrdId() bool {
	if o != nil && !IsNil(o.ClOrdId) {
		return true
	}

	return false
}

// SetClOrdId gets a reference to the given string and assigns it to the ClOrdId field.
func (o *CreateTradeBatchOrdersV5RespDataInner) SetClOrdId(v string) {
	o.ClOrdId = &v
}

// GetOrdId returns the OrdId field value if set, zero value otherwise.
func (o *CreateTradeBatchOrdersV5RespDataInner) GetOrdId() string {
	if o == nil || IsNil(o.OrdId) {
		var ret string
		return ret
	}
	return *o.OrdId
}

// GetOrdIdOk returns a tuple with the OrdId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTradeBatchOrdersV5RespDataInner) GetOrdIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrdId) {
		return nil, false
	}
	return o.OrdId, true
}

// HasOrdId returns a boolean if a field has been set.
func (o *CreateTradeBatchOrdersV5RespDataInner) HasOrdId() bool {
	if o != nil && !IsNil(o.OrdId) {
		return true
	}

	return false
}

// SetOrdId gets a reference to the given string and assigns it to the OrdId field.
func (o *CreateTradeBatchOrdersV5RespDataInner) SetOrdId(v string) {
	o.OrdId = &v
}

// GetSCode returns the SCode field value if set, zero value otherwise.
func (o *CreateTradeBatchOrdersV5RespDataInner) GetSCode() string {
	if o == nil || IsNil(o.SCode) {
		var ret string
		return ret
	}
	return *o.SCode
}

// GetSCodeOk returns a tuple with the SCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTradeBatchOrdersV5RespDataInner) GetSCodeOk() (*string, bool) {
	if o == nil || IsNil(o.SCode) {
		return nil, false
	}
	return o.SCode, true
}

// HasSCode returns a boolean if a field has been set.
func (o *CreateTradeBatchOrdersV5RespDataInner) HasSCode() bool {
	if o != nil && !IsNil(o.SCode) {
		return true
	}

	return false
}

// SetSCode gets a reference to the given string and assigns it to the SCode field.
func (o *CreateTradeBatchOrdersV5RespDataInner) SetSCode(v string) {
	o.SCode = &v
}

// GetSMsg returns the SMsg field value if set, zero value otherwise.
func (o *CreateTradeBatchOrdersV5RespDataInner) GetSMsg() string {
	if o == nil || IsNil(o.SMsg) {
		var ret string
		return ret
	}
	return *o.SMsg
}

// GetSMsgOk returns a tuple with the SMsg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTradeBatchOrdersV5RespDataInner) GetSMsgOk() (*string, bool) {
	if o == nil || IsNil(o.SMsg) {
		return nil, false
	}
	return o.SMsg, true
}

// HasSMsg returns a boolean if a field has been set.
func (o *CreateTradeBatchOrdersV5RespDataInner) HasSMsg() bool {
	if o != nil && !IsNil(o.SMsg) {
		return true
	}

	return false
}

// SetSMsg gets a reference to the given string and assigns it to the SMsg field.
func (o *CreateTradeBatchOrdersV5RespDataInner) SetSMsg(v string) {
	o.SMsg = &v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *CreateTradeBatchOrdersV5RespDataInner) GetTag() string {
	if o == nil || IsNil(o.Tag) {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTradeBatchOrdersV5RespDataInner) GetTagOk() (*string, bool) {
	if o == nil || IsNil(o.Tag) {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *CreateTradeBatchOrdersV5RespDataInner) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *CreateTradeBatchOrdersV5RespDataInner) SetTag(v string) {
	o.Tag = &v
}

// GetTs returns the Ts field value if set, zero value otherwise.
func (o *CreateTradeBatchOrdersV5RespDataInner) GetTs() string {
	if o == nil || IsNil(o.Ts) {
		var ret string
		return ret
	}
	return *o.Ts
}

// GetTsOk returns a tuple with the Ts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTradeBatchOrdersV5RespDataInner) GetTsOk() (*string, bool) {
	if o == nil || IsNil(o.Ts) {
		return nil, false
	}
	return o.Ts, true
}

// HasTs returns a boolean if a field has been set.
func (o *CreateTradeBatchOrdersV5RespDataInner) HasTs() bool {
	if o != nil && !IsNil(o.Ts) {
		return true
	}

	return false
}

// SetTs gets a reference to the given string and assigns it to the Ts field.
func (o *CreateTradeBatchOrdersV5RespDataInner) SetTs(v string) {
	o.Ts = &v
}

func (o CreateTradeBatchOrdersV5RespDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTradeBatchOrdersV5RespDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClOrdId) {
		toSerialize["clOrdId"] = o.ClOrdId
	}
	if !IsNil(o.OrdId) {
		toSerialize["ordId"] = o.OrdId
	}
	if !IsNil(o.SCode) {
		toSerialize["sCode"] = o.SCode
	}
	if !IsNil(o.SMsg) {
		toSerialize["sMsg"] = o.SMsg
	}
	if !IsNil(o.Tag) {
		toSerialize["tag"] = o.Tag
	}
	if !IsNil(o.Ts) {
		toSerialize["ts"] = o.Ts
	}
	return toSerialize, nil
}

type NullableCreateTradeBatchOrdersV5RespDataInner struct {
	value *CreateTradeBatchOrdersV5RespDataInner
	isSet bool
}

func (v NullableCreateTradeBatchOrdersV5RespDataInner) Get() *CreateTradeBatchOrdersV5RespDataInner {
	return v.value
}

func (v *NullableCreateTradeBatchOrdersV5RespDataInner) Set(val *CreateTradeBatchOrdersV5RespDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTradeBatchOrdersV5RespDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTradeBatchOrdersV5RespDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTradeBatchOrdersV5RespDataInner(val *CreateTradeBatchOrdersV5RespDataInner) *NullableCreateTradeBatchOrdersV5RespDataInner {
	return &NullableCreateTradeBatchOrdersV5RespDataInner{value: val, isSet: true}
}

func (v NullableCreateTradeBatchOrdersV5RespDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTradeBatchOrdersV5RespDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


