/*
Okx Rest API

OpenAPI specification for Okx cryptocurrency exchange - Rest API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rest

import (
	"encoding/json"
)

// checks if the GetFiatDepositPaymentMethodsV5RespData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFiatDepositPaymentMethodsV5RespData{}

// GetFiatDepositPaymentMethodsV5RespData struct for GetFiatDepositPaymentMethodsV5RespData
type GetFiatDepositPaymentMethodsV5RespData struct {
	// An array containing information about payment accounts associated with the currency and method.
	Accounts []GetFiatDepositPaymentMethodsV5RespDataAccountsInner `json:"accounts,omitempty"`
	// Fiat currency
	Ccy *string `json:"ccy,omitempty"`
	// The fee rate for each deposit, expressed as a percentage  e.g. `0.02` represents 2 percent fee for each transaction.
	FeeRate *string `json:"feeRate,omitempty"`
	Limits *GetFiatDepositPaymentMethodsV5RespDataLimits `json:"limits,omitempty"`
	// The minimum fee for each deposit
	MinFee *string `json:"minFee,omitempty"`
	// The payment method associated with the currency  `TR_BANKS`  `PIX`  `SEPA`
	PaymentMethod *string `json:"paymentMethod,omitempty"`
}

// NewGetFiatDepositPaymentMethodsV5RespData instantiates a new GetFiatDepositPaymentMethodsV5RespData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFiatDepositPaymentMethodsV5RespData() *GetFiatDepositPaymentMethodsV5RespData {
	this := GetFiatDepositPaymentMethodsV5RespData{}
	var ccy string = ""
	this.Ccy = &ccy
	var feeRate string = ""
	this.FeeRate = &feeRate
	var minFee string = ""
	this.MinFee = &minFee
	var paymentMethod string = ""
	this.PaymentMethod = &paymentMethod
	return &this
}

// NewGetFiatDepositPaymentMethodsV5RespDataWithDefaults instantiates a new GetFiatDepositPaymentMethodsV5RespData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFiatDepositPaymentMethodsV5RespDataWithDefaults() *GetFiatDepositPaymentMethodsV5RespData {
	this := GetFiatDepositPaymentMethodsV5RespData{}
	var ccy string = ""
	this.Ccy = &ccy
	var feeRate string = ""
	this.FeeRate = &feeRate
	var minFee string = ""
	this.MinFee = &minFee
	var paymentMethod string = ""
	this.PaymentMethod = &paymentMethod
	return &this
}

// GetAccounts returns the Accounts field value if set, zero value otherwise.
func (o *GetFiatDepositPaymentMethodsV5RespData) GetAccounts() []GetFiatDepositPaymentMethodsV5RespDataAccountsInner {
	if o == nil || IsNil(o.Accounts) {
		var ret []GetFiatDepositPaymentMethodsV5RespDataAccountsInner
		return ret
	}
	return o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFiatDepositPaymentMethodsV5RespData) GetAccountsOk() ([]GetFiatDepositPaymentMethodsV5RespDataAccountsInner, bool) {
	if o == nil || IsNil(o.Accounts) {
		return nil, false
	}
	return o.Accounts, true
}

// HasAccounts returns a boolean if a field has been set.
func (o *GetFiatDepositPaymentMethodsV5RespData) HasAccounts() bool {
	if o != nil && !IsNil(o.Accounts) {
		return true
	}

	return false
}

// SetAccounts gets a reference to the given []GetFiatDepositPaymentMethodsV5RespDataAccountsInner and assigns it to the Accounts field.
func (o *GetFiatDepositPaymentMethodsV5RespData) SetAccounts(v []GetFiatDepositPaymentMethodsV5RespDataAccountsInner) {
	o.Accounts = v
}

// GetCcy returns the Ccy field value if set, zero value otherwise.
func (o *GetFiatDepositPaymentMethodsV5RespData) GetCcy() string {
	if o == nil || IsNil(o.Ccy) {
		var ret string
		return ret
	}
	return *o.Ccy
}

// GetCcyOk returns a tuple with the Ccy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFiatDepositPaymentMethodsV5RespData) GetCcyOk() (*string, bool) {
	if o == nil || IsNil(o.Ccy) {
		return nil, false
	}
	return o.Ccy, true
}

// HasCcy returns a boolean if a field has been set.
func (o *GetFiatDepositPaymentMethodsV5RespData) HasCcy() bool {
	if o != nil && !IsNil(o.Ccy) {
		return true
	}

	return false
}

// SetCcy gets a reference to the given string and assigns it to the Ccy field.
func (o *GetFiatDepositPaymentMethodsV5RespData) SetCcy(v string) {
	o.Ccy = &v
}

// GetFeeRate returns the FeeRate field value if set, zero value otherwise.
func (o *GetFiatDepositPaymentMethodsV5RespData) GetFeeRate() string {
	if o == nil || IsNil(o.FeeRate) {
		var ret string
		return ret
	}
	return *o.FeeRate
}

// GetFeeRateOk returns a tuple with the FeeRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFiatDepositPaymentMethodsV5RespData) GetFeeRateOk() (*string, bool) {
	if o == nil || IsNil(o.FeeRate) {
		return nil, false
	}
	return o.FeeRate, true
}

// HasFeeRate returns a boolean if a field has been set.
func (o *GetFiatDepositPaymentMethodsV5RespData) HasFeeRate() bool {
	if o != nil && !IsNil(o.FeeRate) {
		return true
	}

	return false
}

// SetFeeRate gets a reference to the given string and assigns it to the FeeRate field.
func (o *GetFiatDepositPaymentMethodsV5RespData) SetFeeRate(v string) {
	o.FeeRate = &v
}

// GetLimits returns the Limits field value if set, zero value otherwise.
func (o *GetFiatDepositPaymentMethodsV5RespData) GetLimits() GetFiatDepositPaymentMethodsV5RespDataLimits {
	if o == nil || IsNil(o.Limits) {
		var ret GetFiatDepositPaymentMethodsV5RespDataLimits
		return ret
	}
	return *o.Limits
}

// GetLimitsOk returns a tuple with the Limits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFiatDepositPaymentMethodsV5RespData) GetLimitsOk() (*GetFiatDepositPaymentMethodsV5RespDataLimits, bool) {
	if o == nil || IsNil(o.Limits) {
		return nil, false
	}
	return o.Limits, true
}

// HasLimits returns a boolean if a field has been set.
func (o *GetFiatDepositPaymentMethodsV5RespData) HasLimits() bool {
	if o != nil && !IsNil(o.Limits) {
		return true
	}

	return false
}

// SetLimits gets a reference to the given GetFiatDepositPaymentMethodsV5RespDataLimits and assigns it to the Limits field.
func (o *GetFiatDepositPaymentMethodsV5RespData) SetLimits(v GetFiatDepositPaymentMethodsV5RespDataLimits) {
	o.Limits = &v
}

// GetMinFee returns the MinFee field value if set, zero value otherwise.
func (o *GetFiatDepositPaymentMethodsV5RespData) GetMinFee() string {
	if o == nil || IsNil(o.MinFee) {
		var ret string
		return ret
	}
	return *o.MinFee
}

// GetMinFeeOk returns a tuple with the MinFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFiatDepositPaymentMethodsV5RespData) GetMinFeeOk() (*string, bool) {
	if o == nil || IsNil(o.MinFee) {
		return nil, false
	}
	return o.MinFee, true
}

// HasMinFee returns a boolean if a field has been set.
func (o *GetFiatDepositPaymentMethodsV5RespData) HasMinFee() bool {
	if o != nil && !IsNil(o.MinFee) {
		return true
	}

	return false
}

// SetMinFee gets a reference to the given string and assigns it to the MinFee field.
func (o *GetFiatDepositPaymentMethodsV5RespData) SetMinFee(v string) {
	o.MinFee = &v
}

// GetPaymentMethod returns the PaymentMethod field value if set, zero value otherwise.
func (o *GetFiatDepositPaymentMethodsV5RespData) GetPaymentMethod() string {
	if o == nil || IsNil(o.PaymentMethod) {
		var ret string
		return ret
	}
	return *o.PaymentMethod
}

// GetPaymentMethodOk returns a tuple with the PaymentMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFiatDepositPaymentMethodsV5RespData) GetPaymentMethodOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentMethod) {
		return nil, false
	}
	return o.PaymentMethod, true
}

// HasPaymentMethod returns a boolean if a field has been set.
func (o *GetFiatDepositPaymentMethodsV5RespData) HasPaymentMethod() bool {
	if o != nil && !IsNil(o.PaymentMethod) {
		return true
	}

	return false
}

// SetPaymentMethod gets a reference to the given string and assigns it to the PaymentMethod field.
func (o *GetFiatDepositPaymentMethodsV5RespData) SetPaymentMethod(v string) {
	o.PaymentMethod = &v
}

func (o GetFiatDepositPaymentMethodsV5RespData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFiatDepositPaymentMethodsV5RespData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Accounts) {
		toSerialize["accounts"] = o.Accounts
	}
	if !IsNil(o.Ccy) {
		toSerialize["ccy"] = o.Ccy
	}
	if !IsNil(o.FeeRate) {
		toSerialize["feeRate"] = o.FeeRate
	}
	if !IsNil(o.Limits) {
		toSerialize["limits"] = o.Limits
	}
	if !IsNil(o.MinFee) {
		toSerialize["minFee"] = o.MinFee
	}
	if !IsNil(o.PaymentMethod) {
		toSerialize["paymentMethod"] = o.PaymentMethod
	}
	return toSerialize, nil
}

type NullableGetFiatDepositPaymentMethodsV5RespData struct {
	value *GetFiatDepositPaymentMethodsV5RespData
	isSet bool
}

func (v NullableGetFiatDepositPaymentMethodsV5RespData) Get() *GetFiatDepositPaymentMethodsV5RespData {
	return v.value
}

func (v *NullableGetFiatDepositPaymentMethodsV5RespData) Set(val *GetFiatDepositPaymentMethodsV5RespData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFiatDepositPaymentMethodsV5RespData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFiatDepositPaymentMethodsV5RespData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFiatDepositPaymentMethodsV5RespData(val *GetFiatDepositPaymentMethodsV5RespData) *NullableGetFiatDepositPaymentMethodsV5RespData {
	return &NullableGetFiatDepositPaymentMethodsV5RespData{value: val, isSet: true}
}

func (v NullableGetFiatDepositPaymentMethodsV5RespData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFiatDepositPaymentMethodsV5RespData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


