/*
Okx Rest API

OpenAPI specification for Okx cryptocurrency exchange - Rest API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rest

import (
	"encoding/json"
)

// checks if the GetAssetMonthlyStatementV5RespData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAssetMonthlyStatementV5RespData{}

// GetAssetMonthlyStatementV5RespData struct for GetAssetMonthlyStatementV5RespData
type GetAssetMonthlyStatementV5RespData struct {
	// Download file link
	FileHref *string `json:"fileHref,omitempty"`
	// Download link status   \"finished\" \"ongoing\"
	State *string `json:"state,omitempty"`
	// Download link generation time, Unix timestamp format in milliseconds, e.g. `1597026383085`
	Ts *int32 `json:"ts,omitempty"`
}

// NewGetAssetMonthlyStatementV5RespData instantiates a new GetAssetMonthlyStatementV5RespData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAssetMonthlyStatementV5RespData() *GetAssetMonthlyStatementV5RespData {
	this := GetAssetMonthlyStatementV5RespData{}
	var fileHref string = ""
	this.FileHref = &fileHref
	var state string = ""
	this.State = &state
	return &this
}

// NewGetAssetMonthlyStatementV5RespDataWithDefaults instantiates a new GetAssetMonthlyStatementV5RespData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAssetMonthlyStatementV5RespDataWithDefaults() *GetAssetMonthlyStatementV5RespData {
	this := GetAssetMonthlyStatementV5RespData{}
	var fileHref string = ""
	this.FileHref = &fileHref
	var state string = ""
	this.State = &state
	return &this
}

// GetFileHref returns the FileHref field value if set, zero value otherwise.
func (o *GetAssetMonthlyStatementV5RespData) GetFileHref() string {
	if o == nil || IsNil(o.FileHref) {
		var ret string
		return ret
	}
	return *o.FileHref
}

// GetFileHrefOk returns a tuple with the FileHref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAssetMonthlyStatementV5RespData) GetFileHrefOk() (*string, bool) {
	if o == nil || IsNil(o.FileHref) {
		return nil, false
	}
	return o.FileHref, true
}

// HasFileHref returns a boolean if a field has been set.
func (o *GetAssetMonthlyStatementV5RespData) HasFileHref() bool {
	if o != nil && !IsNil(o.FileHref) {
		return true
	}

	return false
}

// SetFileHref gets a reference to the given string and assigns it to the FileHref field.
func (o *GetAssetMonthlyStatementV5RespData) SetFileHref(v string) {
	o.FileHref = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *GetAssetMonthlyStatementV5RespData) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAssetMonthlyStatementV5RespData) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *GetAssetMonthlyStatementV5RespData) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *GetAssetMonthlyStatementV5RespData) SetState(v string) {
	o.State = &v
}

// GetTs returns the Ts field value if set, zero value otherwise.
func (o *GetAssetMonthlyStatementV5RespData) GetTs() int32 {
	if o == nil || IsNil(o.Ts) {
		var ret int32
		return ret
	}
	return *o.Ts
}

// GetTsOk returns a tuple with the Ts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAssetMonthlyStatementV5RespData) GetTsOk() (*int32, bool) {
	if o == nil || IsNil(o.Ts) {
		return nil, false
	}
	return o.Ts, true
}

// HasTs returns a boolean if a field has been set.
func (o *GetAssetMonthlyStatementV5RespData) HasTs() bool {
	if o != nil && !IsNil(o.Ts) {
		return true
	}

	return false
}

// SetTs gets a reference to the given int32 and assigns it to the Ts field.
func (o *GetAssetMonthlyStatementV5RespData) SetTs(v int32) {
	o.Ts = &v
}

func (o GetAssetMonthlyStatementV5RespData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAssetMonthlyStatementV5RespData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FileHref) {
		toSerialize["fileHref"] = o.FileHref
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.Ts) {
		toSerialize["ts"] = o.Ts
	}
	return toSerialize, nil
}

type NullableGetAssetMonthlyStatementV5RespData struct {
	value *GetAssetMonthlyStatementV5RespData
	isSet bool
}

func (v NullableGetAssetMonthlyStatementV5RespData) Get() *GetAssetMonthlyStatementV5RespData {
	return v.value
}

func (v *NullableGetAssetMonthlyStatementV5RespData) Set(val *GetAssetMonthlyStatementV5RespData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAssetMonthlyStatementV5RespData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAssetMonthlyStatementV5RespData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAssetMonthlyStatementV5RespData(val *GetAssetMonthlyStatementV5RespData) *NullableGetAssetMonthlyStatementV5RespData {
	return &NullableGetAssetMonthlyStatementV5RespData{value: val, isSet: true}
}

func (v NullableGetAssetMonthlyStatementV5RespData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAssetMonthlyStatementV5RespData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


