/*
Okx Rest API

OpenAPI specification for Okx cryptocurrency exchange - Rest API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rest

import (
	"encoding/json"
)

// checks if the GetAssetBillsV5RespDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAssetBillsV5RespDataInner{}

// GetAssetBillsV5RespDataInner struct for GetAssetBillsV5RespDataInner
type GetAssetBillsV5RespDataInner struct {
	// Balance at the account level
	Bal *string `json:"bal,omitempty"`
	// Change in balance at the account level
	BalChg *string `json:"balChg,omitempty"`
	// Bill ID
	BillId *string `json:"billId,omitempty"`
	// Account balance currency
	Ccy *string `json:"ccy,omitempty"`
	// Client-supplied ID for transfer or withdrawal
	ClientId *string `json:"clientId,omitempty"`
	// Creation time, Unix timestamp format in milliseconds, e.g.`1597026383085`
	Ts *string `json:"ts,omitempty"`
	// Bill type
	Type *string `json:"type,omitempty"`
}

// NewGetAssetBillsV5RespDataInner instantiates a new GetAssetBillsV5RespDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAssetBillsV5RespDataInner() *GetAssetBillsV5RespDataInner {
	this := GetAssetBillsV5RespDataInner{}
	var bal string = ""
	this.Bal = &bal
	var balChg string = ""
	this.BalChg = &balChg
	var billId string = ""
	this.BillId = &billId
	var ccy string = ""
	this.Ccy = &ccy
	var clientId string = ""
	this.ClientId = &clientId
	var ts string = ""
	this.Ts = &ts
	var type_ string = ""
	this.Type = &type_
	return &this
}

// NewGetAssetBillsV5RespDataInnerWithDefaults instantiates a new GetAssetBillsV5RespDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAssetBillsV5RespDataInnerWithDefaults() *GetAssetBillsV5RespDataInner {
	this := GetAssetBillsV5RespDataInner{}
	var bal string = ""
	this.Bal = &bal
	var balChg string = ""
	this.BalChg = &balChg
	var billId string = ""
	this.BillId = &billId
	var ccy string = ""
	this.Ccy = &ccy
	var clientId string = ""
	this.ClientId = &clientId
	var ts string = ""
	this.Ts = &ts
	var type_ string = ""
	this.Type = &type_
	return &this
}

// GetBal returns the Bal field value if set, zero value otherwise.
func (o *GetAssetBillsV5RespDataInner) GetBal() string {
	if o == nil || IsNil(o.Bal) {
		var ret string
		return ret
	}
	return *o.Bal
}

// GetBalOk returns a tuple with the Bal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAssetBillsV5RespDataInner) GetBalOk() (*string, bool) {
	if o == nil || IsNil(o.Bal) {
		return nil, false
	}
	return o.Bal, true
}

// HasBal returns a boolean if a field has been set.
func (o *GetAssetBillsV5RespDataInner) HasBal() bool {
	if o != nil && !IsNil(o.Bal) {
		return true
	}

	return false
}

// SetBal gets a reference to the given string and assigns it to the Bal field.
func (o *GetAssetBillsV5RespDataInner) SetBal(v string) {
	o.Bal = &v
}

// GetBalChg returns the BalChg field value if set, zero value otherwise.
func (o *GetAssetBillsV5RespDataInner) GetBalChg() string {
	if o == nil || IsNil(o.BalChg) {
		var ret string
		return ret
	}
	return *o.BalChg
}

// GetBalChgOk returns a tuple with the BalChg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAssetBillsV5RespDataInner) GetBalChgOk() (*string, bool) {
	if o == nil || IsNil(o.BalChg) {
		return nil, false
	}
	return o.BalChg, true
}

// HasBalChg returns a boolean if a field has been set.
func (o *GetAssetBillsV5RespDataInner) HasBalChg() bool {
	if o != nil && !IsNil(o.BalChg) {
		return true
	}

	return false
}

// SetBalChg gets a reference to the given string and assigns it to the BalChg field.
func (o *GetAssetBillsV5RespDataInner) SetBalChg(v string) {
	o.BalChg = &v
}

// GetBillId returns the BillId field value if set, zero value otherwise.
func (o *GetAssetBillsV5RespDataInner) GetBillId() string {
	if o == nil || IsNil(o.BillId) {
		var ret string
		return ret
	}
	return *o.BillId
}

// GetBillIdOk returns a tuple with the BillId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAssetBillsV5RespDataInner) GetBillIdOk() (*string, bool) {
	if o == nil || IsNil(o.BillId) {
		return nil, false
	}
	return o.BillId, true
}

// HasBillId returns a boolean if a field has been set.
func (o *GetAssetBillsV5RespDataInner) HasBillId() bool {
	if o != nil && !IsNil(o.BillId) {
		return true
	}

	return false
}

// SetBillId gets a reference to the given string and assigns it to the BillId field.
func (o *GetAssetBillsV5RespDataInner) SetBillId(v string) {
	o.BillId = &v
}

// GetCcy returns the Ccy field value if set, zero value otherwise.
func (o *GetAssetBillsV5RespDataInner) GetCcy() string {
	if o == nil || IsNil(o.Ccy) {
		var ret string
		return ret
	}
	return *o.Ccy
}

// GetCcyOk returns a tuple with the Ccy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAssetBillsV5RespDataInner) GetCcyOk() (*string, bool) {
	if o == nil || IsNil(o.Ccy) {
		return nil, false
	}
	return o.Ccy, true
}

// HasCcy returns a boolean if a field has been set.
func (o *GetAssetBillsV5RespDataInner) HasCcy() bool {
	if o != nil && !IsNil(o.Ccy) {
		return true
	}

	return false
}

// SetCcy gets a reference to the given string and assigns it to the Ccy field.
func (o *GetAssetBillsV5RespDataInner) SetCcy(v string) {
	o.Ccy = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *GetAssetBillsV5RespDataInner) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAssetBillsV5RespDataInner) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *GetAssetBillsV5RespDataInner) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *GetAssetBillsV5RespDataInner) SetClientId(v string) {
	o.ClientId = &v
}

// GetTs returns the Ts field value if set, zero value otherwise.
func (o *GetAssetBillsV5RespDataInner) GetTs() string {
	if o == nil || IsNil(o.Ts) {
		var ret string
		return ret
	}
	return *o.Ts
}

// GetTsOk returns a tuple with the Ts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAssetBillsV5RespDataInner) GetTsOk() (*string, bool) {
	if o == nil || IsNil(o.Ts) {
		return nil, false
	}
	return o.Ts, true
}

// HasTs returns a boolean if a field has been set.
func (o *GetAssetBillsV5RespDataInner) HasTs() bool {
	if o != nil && !IsNil(o.Ts) {
		return true
	}

	return false
}

// SetTs gets a reference to the given string and assigns it to the Ts field.
func (o *GetAssetBillsV5RespDataInner) SetTs(v string) {
	o.Ts = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetAssetBillsV5RespDataInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAssetBillsV5RespDataInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetAssetBillsV5RespDataInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetAssetBillsV5RespDataInner) SetType(v string) {
	o.Type = &v
}

func (o GetAssetBillsV5RespDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAssetBillsV5RespDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Bal) {
		toSerialize["bal"] = o.Bal
	}
	if !IsNil(o.BalChg) {
		toSerialize["balChg"] = o.BalChg
	}
	if !IsNil(o.BillId) {
		toSerialize["billId"] = o.BillId
	}
	if !IsNil(o.Ccy) {
		toSerialize["ccy"] = o.Ccy
	}
	if !IsNil(o.ClientId) {
		toSerialize["clientId"] = o.ClientId
	}
	if !IsNil(o.Ts) {
		toSerialize["ts"] = o.Ts
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableGetAssetBillsV5RespDataInner struct {
	value *GetAssetBillsV5RespDataInner
	isSet bool
}

func (v NullableGetAssetBillsV5RespDataInner) Get() *GetAssetBillsV5RespDataInner {
	return v.value
}

func (v *NullableGetAssetBillsV5RespDataInner) Set(val *GetAssetBillsV5RespDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAssetBillsV5RespDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAssetBillsV5RespDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAssetBillsV5RespDataInner(val *GetAssetBillsV5RespDataInner) *NullableGetAssetBillsV5RespDataInner {
	return &NullableGetAssetBillsV5RespDataInner{value: val, isSet: true}
}

func (v NullableGetAssetBillsV5RespDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAssetBillsV5RespDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


