/*
Okx Rest API

OpenAPI specification for Okx cryptocurrency exchange - Rest API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rest

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateAccountSpotManualBorrowRepayV5Req type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAccountSpotManualBorrowRepayV5Req{}

// CreateAccountSpotManualBorrowRepayV5Req struct for CreateAccountSpotManualBorrowRepayV5Req
type CreateAccountSpotManualBorrowRepayV5Req struct {
	// Amount
	Amt string `json:"amt"`
	// Currency, e.g. `BTC`
	Ccy string `json:"ccy"`
	// Side  `borrow`  `repay`
	Side string `json:"side"`
}

type _CreateAccountSpotManualBorrowRepayV5Req CreateAccountSpotManualBorrowRepayV5Req

// NewCreateAccountSpotManualBorrowRepayV5Req instantiates a new CreateAccountSpotManualBorrowRepayV5Req object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAccountSpotManualBorrowRepayV5Req(amt string, ccy string, side string) *CreateAccountSpotManualBorrowRepayV5Req {
	this := CreateAccountSpotManualBorrowRepayV5Req{}
	this.Amt = amt
	this.Ccy = ccy
	this.Side = side
	return &this
}

// NewCreateAccountSpotManualBorrowRepayV5ReqWithDefaults instantiates a new CreateAccountSpotManualBorrowRepayV5Req object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAccountSpotManualBorrowRepayV5ReqWithDefaults() *CreateAccountSpotManualBorrowRepayV5Req {
	this := CreateAccountSpotManualBorrowRepayV5Req{}
	var amt string = ""
	this.Amt = amt
	var ccy string = ""
	this.Ccy = ccy
	var side string = ""
	this.Side = side
	return &this
}

// GetAmt returns the Amt field value
func (o *CreateAccountSpotManualBorrowRepayV5Req) GetAmt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amt
}

// GetAmtOk returns a tuple with the Amt field value
// and a boolean to check if the value has been set.
func (o *CreateAccountSpotManualBorrowRepayV5Req) GetAmtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amt, true
}

// SetAmt sets field value
func (o *CreateAccountSpotManualBorrowRepayV5Req) SetAmt(v string) {
	o.Amt = v
}

// GetCcy returns the Ccy field value
func (o *CreateAccountSpotManualBorrowRepayV5Req) GetCcy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ccy
}

// GetCcyOk returns a tuple with the Ccy field value
// and a boolean to check if the value has been set.
func (o *CreateAccountSpotManualBorrowRepayV5Req) GetCcyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ccy, true
}

// SetCcy sets field value
func (o *CreateAccountSpotManualBorrowRepayV5Req) SetCcy(v string) {
	o.Ccy = v
}

// GetSide returns the Side field value
func (o *CreateAccountSpotManualBorrowRepayV5Req) GetSide() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Side
}

// GetSideOk returns a tuple with the Side field value
// and a boolean to check if the value has been set.
func (o *CreateAccountSpotManualBorrowRepayV5Req) GetSideOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Side, true
}

// SetSide sets field value
func (o *CreateAccountSpotManualBorrowRepayV5Req) SetSide(v string) {
	o.Side = v
}

func (o CreateAccountSpotManualBorrowRepayV5Req) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAccountSpotManualBorrowRepayV5Req) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amt"] = o.Amt
	toSerialize["ccy"] = o.Ccy
	toSerialize["side"] = o.Side
	return toSerialize, nil
}

func (o *CreateAccountSpotManualBorrowRepayV5Req) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amt",
		"ccy",
		"side",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAccountSpotManualBorrowRepayV5Req := _CreateAccountSpotManualBorrowRepayV5Req{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAccountSpotManualBorrowRepayV5Req)

	if err != nil {
		return err
	}

	*o = CreateAccountSpotManualBorrowRepayV5Req(varCreateAccountSpotManualBorrowRepayV5Req)

	return err
}

type NullableCreateAccountSpotManualBorrowRepayV5Req struct {
	value *CreateAccountSpotManualBorrowRepayV5Req
	isSet bool
}

func (v NullableCreateAccountSpotManualBorrowRepayV5Req) Get() *CreateAccountSpotManualBorrowRepayV5Req {
	return v.value
}

func (v *NullableCreateAccountSpotManualBorrowRepayV5Req) Set(val *CreateAccountSpotManualBorrowRepayV5Req) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAccountSpotManualBorrowRepayV5Req) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAccountSpotManualBorrowRepayV5Req) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAccountSpotManualBorrowRepayV5Req(val *CreateAccountSpotManualBorrowRepayV5Req) *NullableCreateAccountSpotManualBorrowRepayV5Req {
	return &NullableCreateAccountSpotManualBorrowRepayV5Req{value: val, isSet: true}
}

func (v NullableCreateAccountSpotManualBorrowRepayV5Req) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAccountSpotManualBorrowRepayV5Req) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


