/*
OKX v5 API

OpenAPI specification for Okx exchange - Rest API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rest

import (
	"encoding/json"
)

// checks if the GetAccountMaxLoanV5RespDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAccountMaxLoanV5RespDataInner{}

// GetAccountMaxLoanV5RespDataInner struct for GetAccountMaxLoanV5RespDataInner
type GetAccountMaxLoanV5RespDataInner struct {
	// Currency
	Ccy *string `json:"ccy,omitempty"`
	// Instrument ID
	InstId *string `json:"instId,omitempty"`
	// Max loan
	MaxLoan *string `json:"maxLoan,omitempty"`
	// Margin currency
	MgnCcy *string `json:"mgnCcy,omitempty"`
	// Margin mode
	MgnMode *string `json:"mgnMode,omitempty"`
	// Order side  `buy` `sell`
	Side *string `json:"side,omitempty"`
}

// NewGetAccountMaxLoanV5RespDataInner instantiates a new GetAccountMaxLoanV5RespDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccountMaxLoanV5RespDataInner() *GetAccountMaxLoanV5RespDataInner {
	this := GetAccountMaxLoanV5RespDataInner{}
	var ccy string = ""
	this.Ccy = &ccy
	var instId string = ""
	this.InstId = &instId
	var maxLoan string = ""
	this.MaxLoan = &maxLoan
	var mgnCcy string = ""
	this.MgnCcy = &mgnCcy
	var mgnMode string = ""
	this.MgnMode = &mgnMode
	var side string = ""
	this.Side = &side
	return &this
}

// NewGetAccountMaxLoanV5RespDataInnerWithDefaults instantiates a new GetAccountMaxLoanV5RespDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccountMaxLoanV5RespDataInnerWithDefaults() *GetAccountMaxLoanV5RespDataInner {
	this := GetAccountMaxLoanV5RespDataInner{}
	var ccy string = ""
	this.Ccy = &ccy
	var instId string = ""
	this.InstId = &instId
	var maxLoan string = ""
	this.MaxLoan = &maxLoan
	var mgnCcy string = ""
	this.MgnCcy = &mgnCcy
	var mgnMode string = ""
	this.MgnMode = &mgnMode
	var side string = ""
	this.Side = &side
	return &this
}

// GetCcy returns the Ccy field value if set, zero value otherwise.
func (o *GetAccountMaxLoanV5RespDataInner) GetCcy() string {
	if o == nil || IsNil(o.Ccy) {
		var ret string
		return ret
	}
	return *o.Ccy
}

// GetCcyOk returns a tuple with the Ccy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountMaxLoanV5RespDataInner) GetCcyOk() (*string, bool) {
	if o == nil || IsNil(o.Ccy) {
		return nil, false
	}
	return o.Ccy, true
}

// HasCcy returns a boolean if a field has been set.
func (o *GetAccountMaxLoanV5RespDataInner) HasCcy() bool {
	if o != nil && !IsNil(o.Ccy) {
		return true
	}

	return false
}

// SetCcy gets a reference to the given string and assigns it to the Ccy field.
func (o *GetAccountMaxLoanV5RespDataInner) SetCcy(v string) {
	o.Ccy = &v
}

// GetInstId returns the InstId field value if set, zero value otherwise.
func (o *GetAccountMaxLoanV5RespDataInner) GetInstId() string {
	if o == nil || IsNil(o.InstId) {
		var ret string
		return ret
	}
	return *o.InstId
}

// GetInstIdOk returns a tuple with the InstId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountMaxLoanV5RespDataInner) GetInstIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstId) {
		return nil, false
	}
	return o.InstId, true
}

// HasInstId returns a boolean if a field has been set.
func (o *GetAccountMaxLoanV5RespDataInner) HasInstId() bool {
	if o != nil && !IsNil(o.InstId) {
		return true
	}

	return false
}

// SetInstId gets a reference to the given string and assigns it to the InstId field.
func (o *GetAccountMaxLoanV5RespDataInner) SetInstId(v string) {
	o.InstId = &v
}

// GetMaxLoan returns the MaxLoan field value if set, zero value otherwise.
func (o *GetAccountMaxLoanV5RespDataInner) GetMaxLoan() string {
	if o == nil || IsNil(o.MaxLoan) {
		var ret string
		return ret
	}
	return *o.MaxLoan
}

// GetMaxLoanOk returns a tuple with the MaxLoan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountMaxLoanV5RespDataInner) GetMaxLoanOk() (*string, bool) {
	if o == nil || IsNil(o.MaxLoan) {
		return nil, false
	}
	return o.MaxLoan, true
}

// HasMaxLoan returns a boolean if a field has been set.
func (o *GetAccountMaxLoanV5RespDataInner) HasMaxLoan() bool {
	if o != nil && !IsNil(o.MaxLoan) {
		return true
	}

	return false
}

// SetMaxLoan gets a reference to the given string and assigns it to the MaxLoan field.
func (o *GetAccountMaxLoanV5RespDataInner) SetMaxLoan(v string) {
	o.MaxLoan = &v
}

// GetMgnCcy returns the MgnCcy field value if set, zero value otherwise.
func (o *GetAccountMaxLoanV5RespDataInner) GetMgnCcy() string {
	if o == nil || IsNil(o.MgnCcy) {
		var ret string
		return ret
	}
	return *o.MgnCcy
}

// GetMgnCcyOk returns a tuple with the MgnCcy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountMaxLoanV5RespDataInner) GetMgnCcyOk() (*string, bool) {
	if o == nil || IsNil(o.MgnCcy) {
		return nil, false
	}
	return o.MgnCcy, true
}

// HasMgnCcy returns a boolean if a field has been set.
func (o *GetAccountMaxLoanV5RespDataInner) HasMgnCcy() bool {
	if o != nil && !IsNil(o.MgnCcy) {
		return true
	}

	return false
}

// SetMgnCcy gets a reference to the given string and assigns it to the MgnCcy field.
func (o *GetAccountMaxLoanV5RespDataInner) SetMgnCcy(v string) {
	o.MgnCcy = &v
}

// GetMgnMode returns the MgnMode field value if set, zero value otherwise.
func (o *GetAccountMaxLoanV5RespDataInner) GetMgnMode() string {
	if o == nil || IsNil(o.MgnMode) {
		var ret string
		return ret
	}
	return *o.MgnMode
}

// GetMgnModeOk returns a tuple with the MgnMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountMaxLoanV5RespDataInner) GetMgnModeOk() (*string, bool) {
	if o == nil || IsNil(o.MgnMode) {
		return nil, false
	}
	return o.MgnMode, true
}

// HasMgnMode returns a boolean if a field has been set.
func (o *GetAccountMaxLoanV5RespDataInner) HasMgnMode() bool {
	if o != nil && !IsNil(o.MgnMode) {
		return true
	}

	return false
}

// SetMgnMode gets a reference to the given string and assigns it to the MgnMode field.
func (o *GetAccountMaxLoanV5RespDataInner) SetMgnMode(v string) {
	o.MgnMode = &v
}

// GetSide returns the Side field value if set, zero value otherwise.
func (o *GetAccountMaxLoanV5RespDataInner) GetSide() string {
	if o == nil || IsNil(o.Side) {
		var ret string
		return ret
	}
	return *o.Side
}

// GetSideOk returns a tuple with the Side field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountMaxLoanV5RespDataInner) GetSideOk() (*string, bool) {
	if o == nil || IsNil(o.Side) {
		return nil, false
	}
	return o.Side, true
}

// HasSide returns a boolean if a field has been set.
func (o *GetAccountMaxLoanV5RespDataInner) HasSide() bool {
	if o != nil && !IsNil(o.Side) {
		return true
	}

	return false
}

// SetSide gets a reference to the given string and assigns it to the Side field.
func (o *GetAccountMaxLoanV5RespDataInner) SetSide(v string) {
	o.Side = &v
}

func (o GetAccountMaxLoanV5RespDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAccountMaxLoanV5RespDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ccy) {
		toSerialize["ccy"] = o.Ccy
	}
	if !IsNil(o.InstId) {
		toSerialize["instId"] = o.InstId
	}
	if !IsNil(o.MaxLoan) {
		toSerialize["maxLoan"] = o.MaxLoan
	}
	if !IsNil(o.MgnCcy) {
		toSerialize["mgnCcy"] = o.MgnCcy
	}
	if !IsNil(o.MgnMode) {
		toSerialize["mgnMode"] = o.MgnMode
	}
	if !IsNil(o.Side) {
		toSerialize["side"] = o.Side
	}
	return toSerialize, nil
}

type NullableGetAccountMaxLoanV5RespDataInner struct {
	value *GetAccountMaxLoanV5RespDataInner
	isSet bool
}

func (v NullableGetAccountMaxLoanV5RespDataInner) Get() *GetAccountMaxLoanV5RespDataInner {
	return v.value
}

func (v *NullableGetAccountMaxLoanV5RespDataInner) Set(val *GetAccountMaxLoanV5RespDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccountMaxLoanV5RespDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccountMaxLoanV5RespDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccountMaxLoanV5RespDataInner(val *GetAccountMaxLoanV5RespDataInner) *NullableGetAccountMaxLoanV5RespDataInner {
	return &NullableGetAccountMaxLoanV5RespDataInner{value: val, isSet: true}
}

func (v NullableGetAccountMaxLoanV5RespDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccountMaxLoanV5RespDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


