/*
OKX v5 API

OpenAPI specification for Okx exchange - Rest API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rest

import (
	"encoding/json"
)

// checks if the GetPublicSettlementHistoryV5RespDataInnerDetailsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPublicSettlementHistoryV5RespDataInnerDetailsInner{}

// GetPublicSettlementHistoryV5RespDataInnerDetailsInner struct for GetPublicSettlementHistoryV5RespDataInnerDetailsInner
type GetPublicSettlementHistoryV5RespDataInnerDetailsInner struct {
	// Instrument ID
	InstId *string `json:"instId,omitempty"`
	// Settlement price
	SettlePx *string `json:"settlePx,omitempty"`
}

// NewGetPublicSettlementHistoryV5RespDataInnerDetailsInner instantiates a new GetPublicSettlementHistoryV5RespDataInnerDetailsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPublicSettlementHistoryV5RespDataInnerDetailsInner() *GetPublicSettlementHistoryV5RespDataInnerDetailsInner {
	this := GetPublicSettlementHistoryV5RespDataInnerDetailsInner{}
	var instId string = ""
	this.InstId = &instId
	var settlePx string = ""
	this.SettlePx = &settlePx
	return &this
}

// NewGetPublicSettlementHistoryV5RespDataInnerDetailsInnerWithDefaults instantiates a new GetPublicSettlementHistoryV5RespDataInnerDetailsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPublicSettlementHistoryV5RespDataInnerDetailsInnerWithDefaults() *GetPublicSettlementHistoryV5RespDataInnerDetailsInner {
	this := GetPublicSettlementHistoryV5RespDataInnerDetailsInner{}
	var instId string = ""
	this.InstId = &instId
	var settlePx string = ""
	this.SettlePx = &settlePx
	return &this
}

// GetInstId returns the InstId field value if set, zero value otherwise.
func (o *GetPublicSettlementHistoryV5RespDataInnerDetailsInner) GetInstId() string {
	if o == nil || IsNil(o.InstId) {
		var ret string
		return ret
	}
	return *o.InstId
}

// GetInstIdOk returns a tuple with the InstId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPublicSettlementHistoryV5RespDataInnerDetailsInner) GetInstIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstId) {
		return nil, false
	}
	return o.InstId, true
}

// HasInstId returns a boolean if a field has been set.
func (o *GetPublicSettlementHistoryV5RespDataInnerDetailsInner) HasInstId() bool {
	if o != nil && !IsNil(o.InstId) {
		return true
	}

	return false
}

// SetInstId gets a reference to the given string and assigns it to the InstId field.
func (o *GetPublicSettlementHistoryV5RespDataInnerDetailsInner) SetInstId(v string) {
	o.InstId = &v
}

// GetSettlePx returns the SettlePx field value if set, zero value otherwise.
func (o *GetPublicSettlementHistoryV5RespDataInnerDetailsInner) GetSettlePx() string {
	if o == nil || IsNil(o.SettlePx) {
		var ret string
		return ret
	}
	return *o.SettlePx
}

// GetSettlePxOk returns a tuple with the SettlePx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPublicSettlementHistoryV5RespDataInnerDetailsInner) GetSettlePxOk() (*string, bool) {
	if o == nil || IsNil(o.SettlePx) {
		return nil, false
	}
	return o.SettlePx, true
}

// HasSettlePx returns a boolean if a field has been set.
func (o *GetPublicSettlementHistoryV5RespDataInnerDetailsInner) HasSettlePx() bool {
	if o != nil && !IsNil(o.SettlePx) {
		return true
	}

	return false
}

// SetSettlePx gets a reference to the given string and assigns it to the SettlePx field.
func (o *GetPublicSettlementHistoryV5RespDataInnerDetailsInner) SetSettlePx(v string) {
	o.SettlePx = &v
}

func (o GetPublicSettlementHistoryV5RespDataInnerDetailsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPublicSettlementHistoryV5RespDataInnerDetailsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InstId) {
		toSerialize["instId"] = o.InstId
	}
	if !IsNil(o.SettlePx) {
		toSerialize["settlePx"] = o.SettlePx
	}
	return toSerialize, nil
}

type NullableGetPublicSettlementHistoryV5RespDataInnerDetailsInner struct {
	value *GetPublicSettlementHistoryV5RespDataInnerDetailsInner
	isSet bool
}

func (v NullableGetPublicSettlementHistoryV5RespDataInnerDetailsInner) Get() *GetPublicSettlementHistoryV5RespDataInnerDetailsInner {
	return v.value
}

func (v *NullableGetPublicSettlementHistoryV5RespDataInnerDetailsInner) Set(val *GetPublicSettlementHistoryV5RespDataInnerDetailsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPublicSettlementHistoryV5RespDataInnerDetailsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPublicSettlementHistoryV5RespDataInnerDetailsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPublicSettlementHistoryV5RespDataInnerDetailsInner(val *GetPublicSettlementHistoryV5RespDataInnerDetailsInner) *NullableGetPublicSettlementHistoryV5RespDataInnerDetailsInner {
	return &NullableGetPublicSettlementHistoryV5RespDataInnerDetailsInner{value: val, isSet: true}
}

func (v NullableGetPublicSettlementHistoryV5RespDataInnerDetailsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPublicSettlementHistoryV5RespDataInnerDetailsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


