/*
Okx Rest API

OpenAPI specification for Okx cryptocurrency exchange - Rest API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rest

import (
	"encoding/json"
)

// checks if the GetFinanceSavingsBalanceV5RespDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFinanceSavingsBalanceV5RespDataInner{}

// GetFinanceSavingsBalanceV5RespDataInner struct for GetFinanceSavingsBalanceV5RespDataInner
type GetFinanceSavingsBalanceV5RespDataInner struct {
	// Currency amount
	Amt *string `json:"amt,omitempty"`
	// Currency
	Ccy *string `json:"ccy,omitempty"`
	// Currency earnings
	Earnings *string `json:"earnings,omitempty"`
	// Lending amount
	LoanAmt *string `json:"loanAmt,omitempty"`
	// Pending amount
	PendingAmt *string `json:"pendingAmt,omitempty"`
	// Lending rate
	Rate *string `json:"rate,omitempty"`
	// Redempting amount (Deprecated)
	// Deprecated
	RedemptAmt *string `json:"redemptAmt,omitempty"`
}

// NewGetFinanceSavingsBalanceV5RespDataInner instantiates a new GetFinanceSavingsBalanceV5RespDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFinanceSavingsBalanceV5RespDataInner() *GetFinanceSavingsBalanceV5RespDataInner {
	this := GetFinanceSavingsBalanceV5RespDataInner{}
	var amt string = ""
	this.Amt = &amt
	var ccy string = ""
	this.Ccy = &ccy
	var earnings string = ""
	this.Earnings = &earnings
	var loanAmt string = ""
	this.LoanAmt = &loanAmt
	var pendingAmt string = ""
	this.PendingAmt = &pendingAmt
	var rate string = ""
	this.Rate = &rate
	var redemptAmt string = ""
	this.RedemptAmt = &redemptAmt
	return &this
}

// NewGetFinanceSavingsBalanceV5RespDataInnerWithDefaults instantiates a new GetFinanceSavingsBalanceV5RespDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFinanceSavingsBalanceV5RespDataInnerWithDefaults() *GetFinanceSavingsBalanceV5RespDataInner {
	this := GetFinanceSavingsBalanceV5RespDataInner{}
	var amt string = ""
	this.Amt = &amt
	var ccy string = ""
	this.Ccy = &ccy
	var earnings string = ""
	this.Earnings = &earnings
	var loanAmt string = ""
	this.LoanAmt = &loanAmt
	var pendingAmt string = ""
	this.PendingAmt = &pendingAmt
	var rate string = ""
	this.Rate = &rate
	var redemptAmt string = ""
	this.RedemptAmt = &redemptAmt
	return &this
}

// GetAmt returns the Amt field value if set, zero value otherwise.
func (o *GetFinanceSavingsBalanceV5RespDataInner) GetAmt() string {
	if o == nil || IsNil(o.Amt) {
		var ret string
		return ret
	}
	return *o.Amt
}

// GetAmtOk returns a tuple with the Amt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFinanceSavingsBalanceV5RespDataInner) GetAmtOk() (*string, bool) {
	if o == nil || IsNil(o.Amt) {
		return nil, false
	}
	return o.Amt, true
}

// HasAmt returns a boolean if a field has been set.
func (o *GetFinanceSavingsBalanceV5RespDataInner) HasAmt() bool {
	if o != nil && !IsNil(o.Amt) {
		return true
	}

	return false
}

// SetAmt gets a reference to the given string and assigns it to the Amt field.
func (o *GetFinanceSavingsBalanceV5RespDataInner) SetAmt(v string) {
	o.Amt = &v
}

// GetCcy returns the Ccy field value if set, zero value otherwise.
func (o *GetFinanceSavingsBalanceV5RespDataInner) GetCcy() string {
	if o == nil || IsNil(o.Ccy) {
		var ret string
		return ret
	}
	return *o.Ccy
}

// GetCcyOk returns a tuple with the Ccy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFinanceSavingsBalanceV5RespDataInner) GetCcyOk() (*string, bool) {
	if o == nil || IsNil(o.Ccy) {
		return nil, false
	}
	return o.Ccy, true
}

// HasCcy returns a boolean if a field has been set.
func (o *GetFinanceSavingsBalanceV5RespDataInner) HasCcy() bool {
	if o != nil && !IsNil(o.Ccy) {
		return true
	}

	return false
}

// SetCcy gets a reference to the given string and assigns it to the Ccy field.
func (o *GetFinanceSavingsBalanceV5RespDataInner) SetCcy(v string) {
	o.Ccy = &v
}

// GetEarnings returns the Earnings field value if set, zero value otherwise.
func (o *GetFinanceSavingsBalanceV5RespDataInner) GetEarnings() string {
	if o == nil || IsNil(o.Earnings) {
		var ret string
		return ret
	}
	return *o.Earnings
}

// GetEarningsOk returns a tuple with the Earnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFinanceSavingsBalanceV5RespDataInner) GetEarningsOk() (*string, bool) {
	if o == nil || IsNil(o.Earnings) {
		return nil, false
	}
	return o.Earnings, true
}

// HasEarnings returns a boolean if a field has been set.
func (o *GetFinanceSavingsBalanceV5RespDataInner) HasEarnings() bool {
	if o != nil && !IsNil(o.Earnings) {
		return true
	}

	return false
}

// SetEarnings gets a reference to the given string and assigns it to the Earnings field.
func (o *GetFinanceSavingsBalanceV5RespDataInner) SetEarnings(v string) {
	o.Earnings = &v
}

// GetLoanAmt returns the LoanAmt field value if set, zero value otherwise.
func (o *GetFinanceSavingsBalanceV5RespDataInner) GetLoanAmt() string {
	if o == nil || IsNil(o.LoanAmt) {
		var ret string
		return ret
	}
	return *o.LoanAmt
}

// GetLoanAmtOk returns a tuple with the LoanAmt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFinanceSavingsBalanceV5RespDataInner) GetLoanAmtOk() (*string, bool) {
	if o == nil || IsNil(o.LoanAmt) {
		return nil, false
	}
	return o.LoanAmt, true
}

// HasLoanAmt returns a boolean if a field has been set.
func (o *GetFinanceSavingsBalanceV5RespDataInner) HasLoanAmt() bool {
	if o != nil && !IsNil(o.LoanAmt) {
		return true
	}

	return false
}

// SetLoanAmt gets a reference to the given string and assigns it to the LoanAmt field.
func (o *GetFinanceSavingsBalanceV5RespDataInner) SetLoanAmt(v string) {
	o.LoanAmt = &v
}

// GetPendingAmt returns the PendingAmt field value if set, zero value otherwise.
func (o *GetFinanceSavingsBalanceV5RespDataInner) GetPendingAmt() string {
	if o == nil || IsNil(o.PendingAmt) {
		var ret string
		return ret
	}
	return *o.PendingAmt
}

// GetPendingAmtOk returns a tuple with the PendingAmt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFinanceSavingsBalanceV5RespDataInner) GetPendingAmtOk() (*string, bool) {
	if o == nil || IsNil(o.PendingAmt) {
		return nil, false
	}
	return o.PendingAmt, true
}

// HasPendingAmt returns a boolean if a field has been set.
func (o *GetFinanceSavingsBalanceV5RespDataInner) HasPendingAmt() bool {
	if o != nil && !IsNil(o.PendingAmt) {
		return true
	}

	return false
}

// SetPendingAmt gets a reference to the given string and assigns it to the PendingAmt field.
func (o *GetFinanceSavingsBalanceV5RespDataInner) SetPendingAmt(v string) {
	o.PendingAmt = &v
}

// GetRate returns the Rate field value if set, zero value otherwise.
func (o *GetFinanceSavingsBalanceV5RespDataInner) GetRate() string {
	if o == nil || IsNil(o.Rate) {
		var ret string
		return ret
	}
	return *o.Rate
}

// GetRateOk returns a tuple with the Rate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFinanceSavingsBalanceV5RespDataInner) GetRateOk() (*string, bool) {
	if o == nil || IsNil(o.Rate) {
		return nil, false
	}
	return o.Rate, true
}

// HasRate returns a boolean if a field has been set.
func (o *GetFinanceSavingsBalanceV5RespDataInner) HasRate() bool {
	if o != nil && !IsNil(o.Rate) {
		return true
	}

	return false
}

// SetRate gets a reference to the given string and assigns it to the Rate field.
func (o *GetFinanceSavingsBalanceV5RespDataInner) SetRate(v string) {
	o.Rate = &v
}

// GetRedemptAmt returns the RedemptAmt field value if set, zero value otherwise.
// Deprecated
func (o *GetFinanceSavingsBalanceV5RespDataInner) GetRedemptAmt() string {
	if o == nil || IsNil(o.RedemptAmt) {
		var ret string
		return ret
	}
	return *o.RedemptAmt
}

// GetRedemptAmtOk returns a tuple with the RedemptAmt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *GetFinanceSavingsBalanceV5RespDataInner) GetRedemptAmtOk() (*string, bool) {
	if o == nil || IsNil(o.RedemptAmt) {
		return nil, false
	}
	return o.RedemptAmt, true
}

// HasRedemptAmt returns a boolean if a field has been set.
func (o *GetFinanceSavingsBalanceV5RespDataInner) HasRedemptAmt() bool {
	if o != nil && !IsNil(o.RedemptAmt) {
		return true
	}

	return false
}

// SetRedemptAmt gets a reference to the given string and assigns it to the RedemptAmt field.
// Deprecated
func (o *GetFinanceSavingsBalanceV5RespDataInner) SetRedemptAmt(v string) {
	o.RedemptAmt = &v
}

func (o GetFinanceSavingsBalanceV5RespDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFinanceSavingsBalanceV5RespDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amt) {
		toSerialize["amt"] = o.Amt
	}
	if !IsNil(o.Ccy) {
		toSerialize["ccy"] = o.Ccy
	}
	if !IsNil(o.Earnings) {
		toSerialize["earnings"] = o.Earnings
	}
	if !IsNil(o.LoanAmt) {
		toSerialize["loanAmt"] = o.LoanAmt
	}
	if !IsNil(o.PendingAmt) {
		toSerialize["pendingAmt"] = o.PendingAmt
	}
	if !IsNil(o.Rate) {
		toSerialize["rate"] = o.Rate
	}
	if !IsNil(o.RedemptAmt) {
		toSerialize["redemptAmt"] = o.RedemptAmt
	}
	return toSerialize, nil
}

type NullableGetFinanceSavingsBalanceV5RespDataInner struct {
	value *GetFinanceSavingsBalanceV5RespDataInner
	isSet bool
}

func (v NullableGetFinanceSavingsBalanceV5RespDataInner) Get() *GetFinanceSavingsBalanceV5RespDataInner {
	return v.value
}

func (v *NullableGetFinanceSavingsBalanceV5RespDataInner) Set(val *GetFinanceSavingsBalanceV5RespDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFinanceSavingsBalanceV5RespDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFinanceSavingsBalanceV5RespDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFinanceSavingsBalanceV5RespDataInner(val *GetFinanceSavingsBalanceV5RespDataInner) *NullableGetFinanceSavingsBalanceV5RespDataInner {
	return &NullableGetFinanceSavingsBalanceV5RespDataInner{value: val, isSet: true}
}

func (v NullableGetFinanceSavingsBalanceV5RespDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFinanceSavingsBalanceV5RespDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


