/*
Okx Rest API

OpenAPI specification for Okx cryptocurrency exchange - Rest API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rest

import (
	"encoding/json"
)

// checks if the CreateFinanceStakingDefiCancelV5RespDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateFinanceStakingDefiCancelV5RespDataInner{}

// CreateFinanceStakingDefiCancelV5RespDataInner struct for CreateFinanceStakingDefiCancelV5RespDataInner
type CreateFinanceStakingDefiCancelV5RespDataInner struct {
	// Order ID
	OrdId *string `json:"ordId,omitempty"`
	// Order tag
	Tag *string `json:"tag,omitempty"`
}

// NewCreateFinanceStakingDefiCancelV5RespDataInner instantiates a new CreateFinanceStakingDefiCancelV5RespDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFinanceStakingDefiCancelV5RespDataInner() *CreateFinanceStakingDefiCancelV5RespDataInner {
	this := CreateFinanceStakingDefiCancelV5RespDataInner{}
	var ordId string = ""
	this.OrdId = &ordId
	var tag string = ""
	this.Tag = &tag
	return &this
}

// NewCreateFinanceStakingDefiCancelV5RespDataInnerWithDefaults instantiates a new CreateFinanceStakingDefiCancelV5RespDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFinanceStakingDefiCancelV5RespDataInnerWithDefaults() *CreateFinanceStakingDefiCancelV5RespDataInner {
	this := CreateFinanceStakingDefiCancelV5RespDataInner{}
	var ordId string = ""
	this.OrdId = &ordId
	var tag string = ""
	this.Tag = &tag
	return &this
}

// GetOrdId returns the OrdId field value if set, zero value otherwise.
func (o *CreateFinanceStakingDefiCancelV5RespDataInner) GetOrdId() string {
	if o == nil || IsNil(o.OrdId) {
		var ret string
		return ret
	}
	return *o.OrdId
}

// GetOrdIdOk returns a tuple with the OrdId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFinanceStakingDefiCancelV5RespDataInner) GetOrdIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrdId) {
		return nil, false
	}
	return o.OrdId, true
}

// HasOrdId returns a boolean if a field has been set.
func (o *CreateFinanceStakingDefiCancelV5RespDataInner) HasOrdId() bool {
	if o != nil && !IsNil(o.OrdId) {
		return true
	}

	return false
}

// SetOrdId gets a reference to the given string and assigns it to the OrdId field.
func (o *CreateFinanceStakingDefiCancelV5RespDataInner) SetOrdId(v string) {
	o.OrdId = &v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *CreateFinanceStakingDefiCancelV5RespDataInner) GetTag() string {
	if o == nil || IsNil(o.Tag) {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFinanceStakingDefiCancelV5RespDataInner) GetTagOk() (*string, bool) {
	if o == nil || IsNil(o.Tag) {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *CreateFinanceStakingDefiCancelV5RespDataInner) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *CreateFinanceStakingDefiCancelV5RespDataInner) SetTag(v string) {
	o.Tag = &v
}

func (o CreateFinanceStakingDefiCancelV5RespDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateFinanceStakingDefiCancelV5RespDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrdId) {
		toSerialize["ordId"] = o.OrdId
	}
	if !IsNil(o.Tag) {
		toSerialize["tag"] = o.Tag
	}
	return toSerialize, nil
}

type NullableCreateFinanceStakingDefiCancelV5RespDataInner struct {
	value *CreateFinanceStakingDefiCancelV5RespDataInner
	isSet bool
}

func (v NullableCreateFinanceStakingDefiCancelV5RespDataInner) Get() *CreateFinanceStakingDefiCancelV5RespDataInner {
	return v.value
}

func (v *NullableCreateFinanceStakingDefiCancelV5RespDataInner) Set(val *CreateFinanceStakingDefiCancelV5RespDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFinanceStakingDefiCancelV5RespDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFinanceStakingDefiCancelV5RespDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFinanceStakingDefiCancelV5RespDataInner(val *CreateFinanceStakingDefiCancelV5RespDataInner) *NullableCreateFinanceStakingDefiCancelV5RespDataInner {
	return &NullableCreateFinanceStakingDefiCancelV5RespDataInner{value: val, isSet: true}
}

func (v NullableCreateFinanceStakingDefiCancelV5RespDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFinanceStakingDefiCancelV5RespDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


