/*
OKX v5 API

OpenAPI specification for Okx exchange - Rest API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rest

import (
	"encoding/json"
)

// checks if the GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner{}

// GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner struct for GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner
type GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner struct {
	// Repay currency's available balance amount
	RepayAmt *string `json:"repayAmt,omitempty"`
	// Repay currency
	RepayCcy *string `json:"repayCcy,omitempty"`
}

// NewGetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner instantiates a new GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner() *GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner {
	this := GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner{}
	var repayAmt string = ""
	this.RepayAmt = &repayAmt
	var repayCcy string = ""
	this.RepayCcy = &repayCcy
	return &this
}

// NewGetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInnerWithDefaults instantiates a new GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInnerWithDefaults() *GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner {
	this := GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner{}
	var repayAmt string = ""
	this.RepayAmt = &repayAmt
	var repayCcy string = ""
	this.RepayCcy = &repayCcy
	return &this
}

// GetRepayAmt returns the RepayAmt field value if set, zero value otherwise.
func (o *GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner) GetRepayAmt() string {
	if o == nil || IsNil(o.RepayAmt) {
		var ret string
		return ret
	}
	return *o.RepayAmt
}

// GetRepayAmtOk returns a tuple with the RepayAmt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner) GetRepayAmtOk() (*string, bool) {
	if o == nil || IsNil(o.RepayAmt) {
		return nil, false
	}
	return o.RepayAmt, true
}

// HasRepayAmt returns a boolean if a field has been set.
func (o *GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner) HasRepayAmt() bool {
	if o != nil && !IsNil(o.RepayAmt) {
		return true
	}

	return false
}

// SetRepayAmt gets a reference to the given string and assigns it to the RepayAmt field.
func (o *GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner) SetRepayAmt(v string) {
	o.RepayAmt = &v
}

// GetRepayCcy returns the RepayCcy field value if set, zero value otherwise.
func (o *GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner) GetRepayCcy() string {
	if o == nil || IsNil(o.RepayCcy) {
		var ret string
		return ret
	}
	return *o.RepayCcy
}

// GetRepayCcyOk returns a tuple with the RepayCcy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner) GetRepayCcyOk() (*string, bool) {
	if o == nil || IsNil(o.RepayCcy) {
		return nil, false
	}
	return o.RepayCcy, true
}

// HasRepayCcy returns a boolean if a field has been set.
func (o *GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner) HasRepayCcy() bool {
	if o != nil && !IsNil(o.RepayCcy) {
		return true
	}

	return false
}

// SetRepayCcy gets a reference to the given string and assigns it to the RepayCcy field.
func (o *GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner) SetRepayCcy(v string) {
	o.RepayCcy = &v
}

func (o GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RepayAmt) {
		toSerialize["repayAmt"] = o.RepayAmt
	}
	if !IsNil(o.RepayCcy) {
		toSerialize["repayCcy"] = o.RepayCcy
	}
	return toSerialize, nil
}

type NullableGetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner struct {
	value *GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner
	isSet bool
}

func (v NullableGetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner) Get() *GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner {
	return v.value
}

func (v *NullableGetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner) Set(val *GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner(val *GetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner) *NullableGetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner {
	return &NullableGetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner{value: val, isSet: true}
}

func (v NullableGetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTradeOneClickRepayCurrencyListV2V5RespDataInnerRepayDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


