/*
Okx Rest API

OpenAPI specification for Okx cryptocurrency exchange - Rest API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rest

import (
	"encoding/json"
)

// checks if the GetSprdSpreadsV5RespDataInnerLegsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSprdSpreadsV5RespDataInnerLegsInner{}

// GetSprdSpreadsV5RespDataInnerLegsInner struct for GetSprdSpreadsV5RespDataInnerLegsInner
type GetSprdSpreadsV5RespDataInnerLegsInner struct {
	// Instrument ID, e.g. BTC-USD-SWAP
	InstId *string `json:"instId,omitempty"`
	// The direction of the leg of the spread. Valid Values include `buy` and `sell`.
	Side *string `json:"side,omitempty"`
}

// NewGetSprdSpreadsV5RespDataInnerLegsInner instantiates a new GetSprdSpreadsV5RespDataInnerLegsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSprdSpreadsV5RespDataInnerLegsInner() *GetSprdSpreadsV5RespDataInnerLegsInner {
	this := GetSprdSpreadsV5RespDataInnerLegsInner{}
	var instId string = ""
	this.InstId = &instId
	var side string = ""
	this.Side = &side
	return &this
}

// NewGetSprdSpreadsV5RespDataInnerLegsInnerWithDefaults instantiates a new GetSprdSpreadsV5RespDataInnerLegsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSprdSpreadsV5RespDataInnerLegsInnerWithDefaults() *GetSprdSpreadsV5RespDataInnerLegsInner {
	this := GetSprdSpreadsV5RespDataInnerLegsInner{}
	var instId string = ""
	this.InstId = &instId
	var side string = ""
	this.Side = &side
	return &this
}

// GetInstId returns the InstId field value if set, zero value otherwise.
func (o *GetSprdSpreadsV5RespDataInnerLegsInner) GetInstId() string {
	if o == nil || IsNil(o.InstId) {
		var ret string
		return ret
	}
	return *o.InstId
}

// GetInstIdOk returns a tuple with the InstId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSprdSpreadsV5RespDataInnerLegsInner) GetInstIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstId) {
		return nil, false
	}
	return o.InstId, true
}

// HasInstId returns a boolean if a field has been set.
func (o *GetSprdSpreadsV5RespDataInnerLegsInner) HasInstId() bool {
	if o != nil && !IsNil(o.InstId) {
		return true
	}

	return false
}

// SetInstId gets a reference to the given string and assigns it to the InstId field.
func (o *GetSprdSpreadsV5RespDataInnerLegsInner) SetInstId(v string) {
	o.InstId = &v
}

// GetSide returns the Side field value if set, zero value otherwise.
func (o *GetSprdSpreadsV5RespDataInnerLegsInner) GetSide() string {
	if o == nil || IsNil(o.Side) {
		var ret string
		return ret
	}
	return *o.Side
}

// GetSideOk returns a tuple with the Side field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSprdSpreadsV5RespDataInnerLegsInner) GetSideOk() (*string, bool) {
	if o == nil || IsNil(o.Side) {
		return nil, false
	}
	return o.Side, true
}

// HasSide returns a boolean if a field has been set.
func (o *GetSprdSpreadsV5RespDataInnerLegsInner) HasSide() bool {
	if o != nil && !IsNil(o.Side) {
		return true
	}

	return false
}

// SetSide gets a reference to the given string and assigns it to the Side field.
func (o *GetSprdSpreadsV5RespDataInnerLegsInner) SetSide(v string) {
	o.Side = &v
}

func (o GetSprdSpreadsV5RespDataInnerLegsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSprdSpreadsV5RespDataInnerLegsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InstId) {
		toSerialize["instId"] = o.InstId
	}
	if !IsNil(o.Side) {
		toSerialize["side"] = o.Side
	}
	return toSerialize, nil
}

type NullableGetSprdSpreadsV5RespDataInnerLegsInner struct {
	value *GetSprdSpreadsV5RespDataInnerLegsInner
	isSet bool
}

func (v NullableGetSprdSpreadsV5RespDataInnerLegsInner) Get() *GetSprdSpreadsV5RespDataInnerLegsInner {
	return v.value
}

func (v *NullableGetSprdSpreadsV5RespDataInnerLegsInner) Set(val *GetSprdSpreadsV5RespDataInnerLegsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSprdSpreadsV5RespDataInnerLegsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSprdSpreadsV5RespDataInnerLegsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSprdSpreadsV5RespDataInnerLegsInner(val *GetSprdSpreadsV5RespDataInnerLegsInner) *NullableGetSprdSpreadsV5RespDataInnerLegsInner {
	return &NullableGetSprdSpreadsV5RespDataInnerLegsInner{value: val, isSet: true}
}

func (v NullableGetSprdSpreadsV5RespDataInnerLegsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSprdSpreadsV5RespDataInnerLegsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


