/*
OKX v5 API

OpenAPI specification for Okx exchange - Rest API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rest

import (
	"encoding/json"
)

// checks if the CreateFiatCancelWithdrawalV5RespDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateFiatCancelWithdrawalV5RespDataInner{}

// CreateFiatCancelWithdrawalV5RespDataInner struct for CreateFiatCancelWithdrawalV5RespDataInner
type CreateFiatCancelWithdrawalV5RespDataInner struct {
	// Payment Order ID
	OrdId *string `json:"ordId,omitempty"`
	// The state of the transaction, e.g.`canceled`
	State *string `json:"state,omitempty"`
}

// NewCreateFiatCancelWithdrawalV5RespDataInner instantiates a new CreateFiatCancelWithdrawalV5RespDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFiatCancelWithdrawalV5RespDataInner() *CreateFiatCancelWithdrawalV5RespDataInner {
	this := CreateFiatCancelWithdrawalV5RespDataInner{}
	var ordId string = ""
	this.OrdId = &ordId
	var state string = ""
	this.State = &state
	return &this
}

// NewCreateFiatCancelWithdrawalV5RespDataInnerWithDefaults instantiates a new CreateFiatCancelWithdrawalV5RespDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFiatCancelWithdrawalV5RespDataInnerWithDefaults() *CreateFiatCancelWithdrawalV5RespDataInner {
	this := CreateFiatCancelWithdrawalV5RespDataInner{}
	var ordId string = ""
	this.OrdId = &ordId
	var state string = ""
	this.State = &state
	return &this
}

// GetOrdId returns the OrdId field value if set, zero value otherwise.
func (o *CreateFiatCancelWithdrawalV5RespDataInner) GetOrdId() string {
	if o == nil || IsNil(o.OrdId) {
		var ret string
		return ret
	}
	return *o.OrdId
}

// GetOrdIdOk returns a tuple with the OrdId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFiatCancelWithdrawalV5RespDataInner) GetOrdIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrdId) {
		return nil, false
	}
	return o.OrdId, true
}

// HasOrdId returns a boolean if a field has been set.
func (o *CreateFiatCancelWithdrawalV5RespDataInner) HasOrdId() bool {
	if o != nil && !IsNil(o.OrdId) {
		return true
	}

	return false
}

// SetOrdId gets a reference to the given string and assigns it to the OrdId field.
func (o *CreateFiatCancelWithdrawalV5RespDataInner) SetOrdId(v string) {
	o.OrdId = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *CreateFiatCancelWithdrawalV5RespDataInner) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFiatCancelWithdrawalV5RespDataInner) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *CreateFiatCancelWithdrawalV5RespDataInner) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *CreateFiatCancelWithdrawalV5RespDataInner) SetState(v string) {
	o.State = &v
}

func (o CreateFiatCancelWithdrawalV5RespDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateFiatCancelWithdrawalV5RespDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrdId) {
		toSerialize["ordId"] = o.OrdId
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

type NullableCreateFiatCancelWithdrawalV5RespDataInner struct {
	value *CreateFiatCancelWithdrawalV5RespDataInner
	isSet bool
}

func (v NullableCreateFiatCancelWithdrawalV5RespDataInner) Get() *CreateFiatCancelWithdrawalV5RespDataInner {
	return v.value
}

func (v *NullableCreateFiatCancelWithdrawalV5RespDataInner) Set(val *CreateFiatCancelWithdrawalV5RespDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFiatCancelWithdrawalV5RespDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFiatCancelWithdrawalV5RespDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFiatCancelWithdrawalV5RespDataInner(val *CreateFiatCancelWithdrawalV5RespDataInner) *NullableCreateFiatCancelWithdrawalV5RespDataInner {
	return &NullableCreateFiatCancelWithdrawalV5RespDataInner{value: val, isSet: true}
}

func (v NullableCreateFiatCancelWithdrawalV5RespDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFiatCancelWithdrawalV5RespDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


