/*
Okx Rest API

OpenAPI specification for Okx cryptocurrency exchange - Rest API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rest

import (
	"encoding/json"
)

// checks if the GetFiatDepositPaymentMethodsV5RespDataLimits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFiatDepositPaymentMethodsV5RespDataLimits{}

// GetFiatDepositPaymentMethodsV5RespDataLimits An object containing limits for various transaction intervals
type GetFiatDepositPaymentMethodsV5RespDataLimits struct {
	// The daily transaction limit
	DailyLimit *string `json:"dailyLimit,omitempty"`
	// The remaining daily transaction limit
	DailyLimitRemaining *string `json:"dailyLimitRemaining,omitempty"`
	// The lifetime transaction limit. Return the configured value, \"\" if not configured
	LifetimeLimit *string `json:"lifetimeLimit,omitempty"`
	// The maximum amount allowed per transaction
	MaxAmt *string `json:"maxAmt,omitempty"`
	// The minimum amount allowed per transaction
	MinAmt *string `json:"minAmt,omitempty"`
	// The monthly transaction limit
	MonthlyLimit *string `json:"monthlyLimit,omitempty"`
	// The remaining monthly transaction limit
	MonthlyLimitRemaining *string `json:"monthlyLimitRemaining,omitempty"`
	// The weekly transaction limit
	WeeklyLimit *string `json:"weeklyLimit,omitempty"`
	// The remaining weekly transaction limit
	WeeklyLimitRemaining *string `json:"weeklyLimitRemaining,omitempty"`
}

// NewGetFiatDepositPaymentMethodsV5RespDataLimits instantiates a new GetFiatDepositPaymentMethodsV5RespDataLimits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFiatDepositPaymentMethodsV5RespDataLimits() *GetFiatDepositPaymentMethodsV5RespDataLimits {
	this := GetFiatDepositPaymentMethodsV5RespDataLimits{}
	var dailyLimit string = ""
	this.DailyLimit = &dailyLimit
	var dailyLimitRemaining string = ""
	this.DailyLimitRemaining = &dailyLimitRemaining
	var lifetimeLimit string = ""
	this.LifetimeLimit = &lifetimeLimit
	var maxAmt string = ""
	this.MaxAmt = &maxAmt
	var minAmt string = ""
	this.MinAmt = &minAmt
	var monthlyLimit string = ""
	this.MonthlyLimit = &monthlyLimit
	var monthlyLimitRemaining string = ""
	this.MonthlyLimitRemaining = &monthlyLimitRemaining
	var weeklyLimit string = ""
	this.WeeklyLimit = &weeklyLimit
	var weeklyLimitRemaining string = ""
	this.WeeklyLimitRemaining = &weeklyLimitRemaining
	return &this
}

// NewGetFiatDepositPaymentMethodsV5RespDataLimitsWithDefaults instantiates a new GetFiatDepositPaymentMethodsV5RespDataLimits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFiatDepositPaymentMethodsV5RespDataLimitsWithDefaults() *GetFiatDepositPaymentMethodsV5RespDataLimits {
	this := GetFiatDepositPaymentMethodsV5RespDataLimits{}
	var dailyLimit string = ""
	this.DailyLimit = &dailyLimit
	var dailyLimitRemaining string = ""
	this.DailyLimitRemaining = &dailyLimitRemaining
	var lifetimeLimit string = ""
	this.LifetimeLimit = &lifetimeLimit
	var maxAmt string = ""
	this.MaxAmt = &maxAmt
	var minAmt string = ""
	this.MinAmt = &minAmt
	var monthlyLimit string = ""
	this.MonthlyLimit = &monthlyLimit
	var monthlyLimitRemaining string = ""
	this.MonthlyLimitRemaining = &monthlyLimitRemaining
	var weeklyLimit string = ""
	this.WeeklyLimit = &weeklyLimit
	var weeklyLimitRemaining string = ""
	this.WeeklyLimitRemaining = &weeklyLimitRemaining
	return &this
}

// GetDailyLimit returns the DailyLimit field value if set, zero value otherwise.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) GetDailyLimit() string {
	if o == nil || IsNil(o.DailyLimit) {
		var ret string
		return ret
	}
	return *o.DailyLimit
}

// GetDailyLimitOk returns a tuple with the DailyLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) GetDailyLimitOk() (*string, bool) {
	if o == nil || IsNil(o.DailyLimit) {
		return nil, false
	}
	return o.DailyLimit, true
}

// HasDailyLimit returns a boolean if a field has been set.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) HasDailyLimit() bool {
	if o != nil && !IsNil(o.DailyLimit) {
		return true
	}

	return false
}

// SetDailyLimit gets a reference to the given string and assigns it to the DailyLimit field.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) SetDailyLimit(v string) {
	o.DailyLimit = &v
}

// GetDailyLimitRemaining returns the DailyLimitRemaining field value if set, zero value otherwise.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) GetDailyLimitRemaining() string {
	if o == nil || IsNil(o.DailyLimitRemaining) {
		var ret string
		return ret
	}
	return *o.DailyLimitRemaining
}

// GetDailyLimitRemainingOk returns a tuple with the DailyLimitRemaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) GetDailyLimitRemainingOk() (*string, bool) {
	if o == nil || IsNil(o.DailyLimitRemaining) {
		return nil, false
	}
	return o.DailyLimitRemaining, true
}

// HasDailyLimitRemaining returns a boolean if a field has been set.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) HasDailyLimitRemaining() bool {
	if o != nil && !IsNil(o.DailyLimitRemaining) {
		return true
	}

	return false
}

// SetDailyLimitRemaining gets a reference to the given string and assigns it to the DailyLimitRemaining field.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) SetDailyLimitRemaining(v string) {
	o.DailyLimitRemaining = &v
}

// GetLifetimeLimit returns the LifetimeLimit field value if set, zero value otherwise.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) GetLifetimeLimit() string {
	if o == nil || IsNil(o.LifetimeLimit) {
		var ret string
		return ret
	}
	return *o.LifetimeLimit
}

// GetLifetimeLimitOk returns a tuple with the LifetimeLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) GetLifetimeLimitOk() (*string, bool) {
	if o == nil || IsNil(o.LifetimeLimit) {
		return nil, false
	}
	return o.LifetimeLimit, true
}

// HasLifetimeLimit returns a boolean if a field has been set.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) HasLifetimeLimit() bool {
	if o != nil && !IsNil(o.LifetimeLimit) {
		return true
	}

	return false
}

// SetLifetimeLimit gets a reference to the given string and assigns it to the LifetimeLimit field.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) SetLifetimeLimit(v string) {
	o.LifetimeLimit = &v
}

// GetMaxAmt returns the MaxAmt field value if set, zero value otherwise.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) GetMaxAmt() string {
	if o == nil || IsNil(o.MaxAmt) {
		var ret string
		return ret
	}
	return *o.MaxAmt
}

// GetMaxAmtOk returns a tuple with the MaxAmt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) GetMaxAmtOk() (*string, bool) {
	if o == nil || IsNil(o.MaxAmt) {
		return nil, false
	}
	return o.MaxAmt, true
}

// HasMaxAmt returns a boolean if a field has been set.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) HasMaxAmt() bool {
	if o != nil && !IsNil(o.MaxAmt) {
		return true
	}

	return false
}

// SetMaxAmt gets a reference to the given string and assigns it to the MaxAmt field.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) SetMaxAmt(v string) {
	o.MaxAmt = &v
}

// GetMinAmt returns the MinAmt field value if set, zero value otherwise.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) GetMinAmt() string {
	if o == nil || IsNil(o.MinAmt) {
		var ret string
		return ret
	}
	return *o.MinAmt
}

// GetMinAmtOk returns a tuple with the MinAmt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) GetMinAmtOk() (*string, bool) {
	if o == nil || IsNil(o.MinAmt) {
		return nil, false
	}
	return o.MinAmt, true
}

// HasMinAmt returns a boolean if a field has been set.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) HasMinAmt() bool {
	if o != nil && !IsNil(o.MinAmt) {
		return true
	}

	return false
}

// SetMinAmt gets a reference to the given string and assigns it to the MinAmt field.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) SetMinAmt(v string) {
	o.MinAmt = &v
}

// GetMonthlyLimit returns the MonthlyLimit field value if set, zero value otherwise.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) GetMonthlyLimit() string {
	if o == nil || IsNil(o.MonthlyLimit) {
		var ret string
		return ret
	}
	return *o.MonthlyLimit
}

// GetMonthlyLimitOk returns a tuple with the MonthlyLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) GetMonthlyLimitOk() (*string, bool) {
	if o == nil || IsNil(o.MonthlyLimit) {
		return nil, false
	}
	return o.MonthlyLimit, true
}

// HasMonthlyLimit returns a boolean if a field has been set.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) HasMonthlyLimit() bool {
	if o != nil && !IsNil(o.MonthlyLimit) {
		return true
	}

	return false
}

// SetMonthlyLimit gets a reference to the given string and assigns it to the MonthlyLimit field.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) SetMonthlyLimit(v string) {
	o.MonthlyLimit = &v
}

// GetMonthlyLimitRemaining returns the MonthlyLimitRemaining field value if set, zero value otherwise.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) GetMonthlyLimitRemaining() string {
	if o == nil || IsNil(o.MonthlyLimitRemaining) {
		var ret string
		return ret
	}
	return *o.MonthlyLimitRemaining
}

// GetMonthlyLimitRemainingOk returns a tuple with the MonthlyLimitRemaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) GetMonthlyLimitRemainingOk() (*string, bool) {
	if o == nil || IsNil(o.MonthlyLimitRemaining) {
		return nil, false
	}
	return o.MonthlyLimitRemaining, true
}

// HasMonthlyLimitRemaining returns a boolean if a field has been set.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) HasMonthlyLimitRemaining() bool {
	if o != nil && !IsNil(o.MonthlyLimitRemaining) {
		return true
	}

	return false
}

// SetMonthlyLimitRemaining gets a reference to the given string and assigns it to the MonthlyLimitRemaining field.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) SetMonthlyLimitRemaining(v string) {
	o.MonthlyLimitRemaining = &v
}

// GetWeeklyLimit returns the WeeklyLimit field value if set, zero value otherwise.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) GetWeeklyLimit() string {
	if o == nil || IsNil(o.WeeklyLimit) {
		var ret string
		return ret
	}
	return *o.WeeklyLimit
}

// GetWeeklyLimitOk returns a tuple with the WeeklyLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) GetWeeklyLimitOk() (*string, bool) {
	if o == nil || IsNil(o.WeeklyLimit) {
		return nil, false
	}
	return o.WeeklyLimit, true
}

// HasWeeklyLimit returns a boolean if a field has been set.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) HasWeeklyLimit() bool {
	if o != nil && !IsNil(o.WeeklyLimit) {
		return true
	}

	return false
}

// SetWeeklyLimit gets a reference to the given string and assigns it to the WeeklyLimit field.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) SetWeeklyLimit(v string) {
	o.WeeklyLimit = &v
}

// GetWeeklyLimitRemaining returns the WeeklyLimitRemaining field value if set, zero value otherwise.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) GetWeeklyLimitRemaining() string {
	if o == nil || IsNil(o.WeeklyLimitRemaining) {
		var ret string
		return ret
	}
	return *o.WeeklyLimitRemaining
}

// GetWeeklyLimitRemainingOk returns a tuple with the WeeklyLimitRemaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) GetWeeklyLimitRemainingOk() (*string, bool) {
	if o == nil || IsNil(o.WeeklyLimitRemaining) {
		return nil, false
	}
	return o.WeeklyLimitRemaining, true
}

// HasWeeklyLimitRemaining returns a boolean if a field has been set.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) HasWeeklyLimitRemaining() bool {
	if o != nil && !IsNil(o.WeeklyLimitRemaining) {
		return true
	}

	return false
}

// SetWeeklyLimitRemaining gets a reference to the given string and assigns it to the WeeklyLimitRemaining field.
func (o *GetFiatDepositPaymentMethodsV5RespDataLimits) SetWeeklyLimitRemaining(v string) {
	o.WeeklyLimitRemaining = &v
}

func (o GetFiatDepositPaymentMethodsV5RespDataLimits) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFiatDepositPaymentMethodsV5RespDataLimits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DailyLimit) {
		toSerialize["dailyLimit"] = o.DailyLimit
	}
	if !IsNil(o.DailyLimitRemaining) {
		toSerialize["dailyLimitRemaining"] = o.DailyLimitRemaining
	}
	if !IsNil(o.LifetimeLimit) {
		toSerialize["lifetimeLimit"] = o.LifetimeLimit
	}
	if !IsNil(o.MaxAmt) {
		toSerialize["maxAmt"] = o.MaxAmt
	}
	if !IsNil(o.MinAmt) {
		toSerialize["minAmt"] = o.MinAmt
	}
	if !IsNil(o.MonthlyLimit) {
		toSerialize["monthlyLimit"] = o.MonthlyLimit
	}
	if !IsNil(o.MonthlyLimitRemaining) {
		toSerialize["monthlyLimitRemaining"] = o.MonthlyLimitRemaining
	}
	if !IsNil(o.WeeklyLimit) {
		toSerialize["weeklyLimit"] = o.WeeklyLimit
	}
	if !IsNil(o.WeeklyLimitRemaining) {
		toSerialize["weeklyLimitRemaining"] = o.WeeklyLimitRemaining
	}
	return toSerialize, nil
}

type NullableGetFiatDepositPaymentMethodsV5RespDataLimits struct {
	value *GetFiatDepositPaymentMethodsV5RespDataLimits
	isSet bool
}

func (v NullableGetFiatDepositPaymentMethodsV5RespDataLimits) Get() *GetFiatDepositPaymentMethodsV5RespDataLimits {
	return v.value
}

func (v *NullableGetFiatDepositPaymentMethodsV5RespDataLimits) Set(val *GetFiatDepositPaymentMethodsV5RespDataLimits) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFiatDepositPaymentMethodsV5RespDataLimits) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFiatDepositPaymentMethodsV5RespDataLimits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFiatDepositPaymentMethodsV5RespDataLimits(val *GetFiatDepositPaymentMethodsV5RespDataLimits) *NullableGetFiatDepositPaymentMethodsV5RespDataLimits {
	return &NullableGetFiatDepositPaymentMethodsV5RespDataLimits{value: val, isSet: true}
}

func (v NullableGetFiatDepositPaymentMethodsV5RespDataLimits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFiatDepositPaymentMethodsV5RespDataLimits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


