/*
Okx Rest API

OpenAPI specification for Okx cryptocurrency exchange - Rest API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rest

import (
	"encoding/json"
)

// checks if the CreateRfqMakerInstrumentSettingsV5ReqDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRfqMakerInstrumentSettingsV5ReqDataInner{}

// CreateRfqMakerInstrumentSettingsV5ReqDataInner struct for CreateRfqMakerInstrumentSettingsV5ReqDataInner
type CreateRfqMakerInstrumentSettingsV5ReqDataInner struct {
	// Instrument family. Required for `FUTURES`, `OPTION` and `SWAP` only.
	InstFamily *string `json:"instFamily,omitempty"`
	// Instrument ID. Required for `SPOT` only.
	InstId *string `json:"instId,omitempty"`
	// Price bands in unit of ticks, measured against mark price.   Setting makerPxBand to 1 tick means:   If Bid price > Mark + 1 tick, it will be stopped   If Ask price < Mark - 1 tick, It will be stopped
	MakerPxBand *string `json:"makerPxBand,omitempty"`
	// Max trade quantity for the product(s).   For `FUTURES`, `OPTION` and `SWAP`, the max quantity of the RFQ/Quote is in unit of contracts. For `SPOT`, this parameter is in base currency.
	MaxBlockSz *string `json:"maxBlockSz,omitempty"`
}

// NewCreateRfqMakerInstrumentSettingsV5ReqDataInner instantiates a new CreateRfqMakerInstrumentSettingsV5ReqDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRfqMakerInstrumentSettingsV5ReqDataInner() *CreateRfqMakerInstrumentSettingsV5ReqDataInner {
	this := CreateRfqMakerInstrumentSettingsV5ReqDataInner{}
	var instFamily string = ""
	this.InstFamily = &instFamily
	var instId string = ""
	this.InstId = &instId
	var makerPxBand string = ""
	this.MakerPxBand = &makerPxBand
	var maxBlockSz string = ""
	this.MaxBlockSz = &maxBlockSz
	return &this
}

// NewCreateRfqMakerInstrumentSettingsV5ReqDataInnerWithDefaults instantiates a new CreateRfqMakerInstrumentSettingsV5ReqDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRfqMakerInstrumentSettingsV5ReqDataInnerWithDefaults() *CreateRfqMakerInstrumentSettingsV5ReqDataInner {
	this := CreateRfqMakerInstrumentSettingsV5ReqDataInner{}
	var instFamily string = ""
	this.InstFamily = &instFamily
	var instId string = ""
	this.InstId = &instId
	var makerPxBand string = ""
	this.MakerPxBand = &makerPxBand
	var maxBlockSz string = ""
	this.MaxBlockSz = &maxBlockSz
	return &this
}

// GetInstFamily returns the InstFamily field value if set, zero value otherwise.
func (o *CreateRfqMakerInstrumentSettingsV5ReqDataInner) GetInstFamily() string {
	if o == nil || IsNil(o.InstFamily) {
		var ret string
		return ret
	}
	return *o.InstFamily
}

// GetInstFamilyOk returns a tuple with the InstFamily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRfqMakerInstrumentSettingsV5ReqDataInner) GetInstFamilyOk() (*string, bool) {
	if o == nil || IsNil(o.InstFamily) {
		return nil, false
	}
	return o.InstFamily, true
}

// HasInstFamily returns a boolean if a field has been set.
func (o *CreateRfqMakerInstrumentSettingsV5ReqDataInner) HasInstFamily() bool {
	if o != nil && !IsNil(o.InstFamily) {
		return true
	}

	return false
}

// SetInstFamily gets a reference to the given string and assigns it to the InstFamily field.
func (o *CreateRfqMakerInstrumentSettingsV5ReqDataInner) SetInstFamily(v string) {
	o.InstFamily = &v
}

// GetInstId returns the InstId field value if set, zero value otherwise.
func (o *CreateRfqMakerInstrumentSettingsV5ReqDataInner) GetInstId() string {
	if o == nil || IsNil(o.InstId) {
		var ret string
		return ret
	}
	return *o.InstId
}

// GetInstIdOk returns a tuple with the InstId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRfqMakerInstrumentSettingsV5ReqDataInner) GetInstIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstId) {
		return nil, false
	}
	return o.InstId, true
}

// HasInstId returns a boolean if a field has been set.
func (o *CreateRfqMakerInstrumentSettingsV5ReqDataInner) HasInstId() bool {
	if o != nil && !IsNil(o.InstId) {
		return true
	}

	return false
}

// SetInstId gets a reference to the given string and assigns it to the InstId field.
func (o *CreateRfqMakerInstrumentSettingsV5ReqDataInner) SetInstId(v string) {
	o.InstId = &v
}

// GetMakerPxBand returns the MakerPxBand field value if set, zero value otherwise.
func (o *CreateRfqMakerInstrumentSettingsV5ReqDataInner) GetMakerPxBand() string {
	if o == nil || IsNil(o.MakerPxBand) {
		var ret string
		return ret
	}
	return *o.MakerPxBand
}

// GetMakerPxBandOk returns a tuple with the MakerPxBand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRfqMakerInstrumentSettingsV5ReqDataInner) GetMakerPxBandOk() (*string, bool) {
	if o == nil || IsNil(o.MakerPxBand) {
		return nil, false
	}
	return o.MakerPxBand, true
}

// HasMakerPxBand returns a boolean if a field has been set.
func (o *CreateRfqMakerInstrumentSettingsV5ReqDataInner) HasMakerPxBand() bool {
	if o != nil && !IsNil(o.MakerPxBand) {
		return true
	}

	return false
}

// SetMakerPxBand gets a reference to the given string and assigns it to the MakerPxBand field.
func (o *CreateRfqMakerInstrumentSettingsV5ReqDataInner) SetMakerPxBand(v string) {
	o.MakerPxBand = &v
}

// GetMaxBlockSz returns the MaxBlockSz field value if set, zero value otherwise.
func (o *CreateRfqMakerInstrumentSettingsV5ReqDataInner) GetMaxBlockSz() string {
	if o == nil || IsNil(o.MaxBlockSz) {
		var ret string
		return ret
	}
	return *o.MaxBlockSz
}

// GetMaxBlockSzOk returns a tuple with the MaxBlockSz field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRfqMakerInstrumentSettingsV5ReqDataInner) GetMaxBlockSzOk() (*string, bool) {
	if o == nil || IsNil(o.MaxBlockSz) {
		return nil, false
	}
	return o.MaxBlockSz, true
}

// HasMaxBlockSz returns a boolean if a field has been set.
func (o *CreateRfqMakerInstrumentSettingsV5ReqDataInner) HasMaxBlockSz() bool {
	if o != nil && !IsNil(o.MaxBlockSz) {
		return true
	}

	return false
}

// SetMaxBlockSz gets a reference to the given string and assigns it to the MaxBlockSz field.
func (o *CreateRfqMakerInstrumentSettingsV5ReqDataInner) SetMaxBlockSz(v string) {
	o.MaxBlockSz = &v
}

func (o CreateRfqMakerInstrumentSettingsV5ReqDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRfqMakerInstrumentSettingsV5ReqDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InstFamily) {
		toSerialize["instFamily"] = o.InstFamily
	}
	if !IsNil(o.InstId) {
		toSerialize["instId"] = o.InstId
	}
	if !IsNil(o.MakerPxBand) {
		toSerialize["makerPxBand"] = o.MakerPxBand
	}
	if !IsNil(o.MaxBlockSz) {
		toSerialize["maxBlockSz"] = o.MaxBlockSz
	}
	return toSerialize, nil
}

type NullableCreateRfqMakerInstrumentSettingsV5ReqDataInner struct {
	value *CreateRfqMakerInstrumentSettingsV5ReqDataInner
	isSet bool
}

func (v NullableCreateRfqMakerInstrumentSettingsV5ReqDataInner) Get() *CreateRfqMakerInstrumentSettingsV5ReqDataInner {
	return v.value
}

func (v *NullableCreateRfqMakerInstrumentSettingsV5ReqDataInner) Set(val *CreateRfqMakerInstrumentSettingsV5ReqDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRfqMakerInstrumentSettingsV5ReqDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRfqMakerInstrumentSettingsV5ReqDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRfqMakerInstrumentSettingsV5ReqDataInner(val *CreateRfqMakerInstrumentSettingsV5ReqDataInner) *NullableCreateRfqMakerInstrumentSettingsV5ReqDataInner {
	return &NullableCreateRfqMakerInstrumentSettingsV5ReqDataInner{value: val, isSet: true}
}

func (v NullableCreateRfqMakerInstrumentSettingsV5ReqDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRfqMakerInstrumentSettingsV5ReqDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


